// Package java - frameworks.go provides Java framework pattern registry
// All Java framework patterns should be registered here
package java

import (
	"github.com/hatlesswizard/inputtracer/pkg/sources/common"
)

// Registry is the global Java framework pattern registry
var Registry = common.NewFrameworkPatternRegistry("java")

// Servlet patterns
var servletPatterns = []*common.FrameworkPattern{
	{
		ID:            "servlet_get_parameter",
		Framework:     "servlet",
		Language:      "java",
		Name:          "HttpServletRequest.getParameter()",
		Description:   "Servlet request parameter",
		ClassPattern:  "^HttpServletRequest$",
		MethodPattern: "^getParameter$",
		SourceType:    common.SourceHTTPGet,
		CarrierClass:  "HttpServletRequest",
		PopulatedFrom: []string{"query string", "form data"},
		Confidence:    0.95,
		Tags:          []string{"servlet"},
	},
	{
		ID:            "servlet_get_parameter_values",
		Framework:     "servlet",
		Language:      "java",
		Name:          "HttpServletRequest.getParameterValues()",
		Description:   "Servlet request parameter array",
		ClassPattern:  "^HttpServletRequest$",
		MethodPattern: "^getParameterValues$",
		SourceType:    common.SourceHTTPGet,
		CarrierClass:  "HttpServletRequest",
		PopulatedFrom: []string{"query string", "form data"},
		Confidence:    0.95,
		Tags:          []string{"servlet"},
	},
	{
		ID:            "servlet_get_parameter_map",
		Framework:     "servlet",
		Language:      "java",
		Name:          "HttpServletRequest.getParameterMap()",
		Description:   "Servlet request parameter map",
		ClassPattern:  "^HttpServletRequest$",
		MethodPattern: "^getParameterMap$",
		SourceType:    common.SourceHTTPGet,
		CarrierClass:  "HttpServletRequest",
		PopulatedFrom: []string{"query string", "form data"},
		Confidence:    0.95,
		Tags:          []string{"servlet"},
	},
	{
		ID:            "servlet_get_header",
		Framework:     "servlet",
		Language:      "java",
		Name:          "HttpServletRequest.getHeader()",
		Description:   "Servlet HTTP header",
		ClassPattern:  "^HttpServletRequest$",
		MethodPattern: "^getHeader$",
		SourceType:    common.SourceHTTPHeader,
		CarrierClass:  "HttpServletRequest",
		PopulatedFrom: []string{"HTTP headers"},
		Confidence:    0.95,
		Tags:          []string{"servlet"},
	},
	{
		ID:            "servlet_get_headers",
		Framework:     "servlet",
		Language:      "java",
		Name:          "HttpServletRequest.getHeaders()",
		Description:   "Servlet HTTP headers",
		ClassPattern:  "^HttpServletRequest$",
		MethodPattern: "^getHeaders$",
		SourceType:    common.SourceHTTPHeader,
		CarrierClass:  "HttpServletRequest",
		PopulatedFrom: []string{"HTTP headers"},
		Confidence:    0.95,
		Tags:          []string{"servlet"},
	},
	{
		ID:            "servlet_get_cookies",
		Framework:     "servlet",
		Language:      "java",
		Name:          "HttpServletRequest.getCookies()",
		Description:   "Servlet cookies",
		ClassPattern:  "^HttpServletRequest$",
		MethodPattern: "^getCookies$",
		SourceType:    common.SourceHTTPCookie,
		CarrierClass:  "HttpServletRequest",
		PopulatedFrom: []string{"cookies"},
		Confidence:    0.95,
		Tags:          []string{"servlet"},
	},
	{
		ID:            "servlet_get_input_stream",
		Framework:     "servlet",
		Language:      "java",
		Name:          "HttpServletRequest.getInputStream()",
		Description:   "Servlet request body stream",
		ClassPattern:  "^HttpServletRequest$",
		MethodPattern: "^getInputStream$",
		SourceType:    common.SourceHTTPBody,
		CarrierClass:  "HttpServletRequest",
		PopulatedFrom: []string{"HTTP body"},
		Confidence:    0.95,
		Tags:          []string{"servlet"},
	},
	{
		ID:            "servlet_get_reader",
		Framework:     "servlet",
		Language:      "java",
		Name:          "HttpServletRequest.getReader()",
		Description:   "Servlet request body reader",
		ClassPattern:  "^HttpServletRequest$",
		MethodPattern: "^getReader$",
		SourceType:    common.SourceHTTPBody,
		CarrierClass:  "HttpServletRequest",
		PopulatedFrom: []string{"HTTP body"},
		Confidence:    0.95,
		Tags:          []string{"servlet"},
	},
	{
		ID:            "servlet_get_path_info",
		Framework:     "servlet",
		Language:      "java",
		Name:          "HttpServletRequest.getPathInfo()",
		Description:   "Servlet URL path info",
		ClassPattern:  "^HttpServletRequest$",
		MethodPattern: "^getPathInfo$",
		SourceType:    common.SourceHTTPPath,
		CarrierClass:  "HttpServletRequest",
		PopulatedFrom: []string{"URL path"},
		Confidence:    0.95,
		Tags:          []string{"servlet"},
	},
	{
		ID:            "servlet_get_query_string",
		Framework:     "servlet",
		Language:      "java",
		Name:          "HttpServletRequest.getQueryString()",
		Description:   "Servlet raw query string",
		ClassPattern:  "^HttpServletRequest$",
		MethodPattern: "^getQueryString$",
		SourceType:    common.SourceHTTPGet,
		CarrierClass:  "HttpServletRequest",
		PopulatedFrom: []string{"query string"},
		Confidence:    0.95,
		Tags:          []string{"servlet"},
	},
	{
		ID:            "servlet_get_parts",
		Framework:     "servlet",
		Language:      "java",
		Name:          "HttpServletRequest.getParts()",
		Description:   "Servlet multipart form data",
		ClassPattern:  "^HttpServletRequest$",
		MethodPattern: "^getParts$",
		SourceType:    common.SourceHTTPFile,
		CarrierClass:  "HttpServletRequest",
		PopulatedFrom: []string{"multipart form"},
		Confidence:    0.95,
		Tags:          []string{"servlet"},
	},
	{
		ID:            "servlet_get_part",
		Framework:     "servlet",
		Language:      "java",
		Name:          "HttpServletRequest.getPart()",
		Description:   "Servlet multipart form part",
		ClassPattern:  "^HttpServletRequest$",
		MethodPattern: "^getPart$",
		SourceType:    common.SourceHTTPFile,
		CarrierClass:  "HttpServletRequest",
		PopulatedFrom: []string{"multipart form"},
		Confidence:    0.95,
		Tags:          []string{"servlet"},
	},
}

// Spring MVC patterns
var springPatterns = []*common.FrameworkPattern{
	{
		ID:            "spring_request_param",
		Framework:     "spring",
		Language:      "java",
		Name:          "Spring @RequestParam",
		Description:   "Spring request parameter annotation",
		MethodPattern: "^RequestParam$",
		SourceType:    common.SourceHTTPGet,
		PopulatedFrom: []string{"query string"},
		Confidence:    0.95,
		Tags:          []string{"framework", "spring", "annotation"},
	},
	{
		ID:            "spring_path_variable",
		Framework:     "spring",
		Language:      "java",
		Name:          "Spring @PathVariable",
		Description:   "Spring path variable annotation",
		MethodPattern: "^PathVariable$",
		SourceType:    common.SourceHTTPPath,
		PopulatedFrom: []string{"URL path"},
		Confidence:    0.95,
		Tags:          []string{"framework", "spring", "annotation"},
	},
	{
		ID:            "spring_request_body",
		Framework:     "spring",
		Language:      "java",
		Name:          "Spring @RequestBody",
		Description:   "Spring request body annotation",
		MethodPattern: "^RequestBody$",
		SourceType:    common.SourceHTTPBody,
		PopulatedFrom: []string{"HTTP body"},
		Confidence:    0.95,
		Tags:          []string{"framework", "spring", "annotation"},
	},
	{
		ID:            "spring_request_header",
		Framework:     "spring",
		Language:      "java",
		Name:          "Spring @RequestHeader",
		Description:   "Spring request header annotation",
		MethodPattern: "^RequestHeader$",
		SourceType:    common.SourceHTTPHeader,
		PopulatedFrom: []string{"HTTP headers"},
		Confidence:    0.95,
		Tags:          []string{"framework", "spring", "annotation"},
	},
	{
		ID:            "spring_cookie_value",
		Framework:     "spring",
		Language:      "java",
		Name:          "Spring @CookieValue",
		Description:   "Spring cookie value annotation",
		MethodPattern: "^CookieValue$",
		SourceType:    common.SourceHTTPCookie,
		PopulatedFrom: []string{"cookies"},
		Confidence:    0.95,
		Tags:          []string{"framework", "spring", "annotation"},
	},
	{
		ID:            "spring_model_attribute",
		Framework:     "spring",
		Language:      "java",
		Name:          "Spring @ModelAttribute",
		Description:   "Spring model attribute annotation",
		MethodPattern: "^ModelAttribute$",
		SourceType:    common.SourceHTTPPost,
		PopulatedFrom: []string{"form data"},
		Confidence:    0.95,
		Tags:          []string{"framework", "spring", "annotation"},
	},
	{
		ID:            "spring_request_part",
		Framework:     "spring",
		Language:      "java",
		Name:          "Spring @RequestPart",
		Description:   "Spring request part annotation for multipart",
		MethodPattern: "^RequestPart$",
		SourceType:    common.SourceHTTPFile,
		PopulatedFrom: []string{"multipart form"},
		Confidence:    0.95,
		Tags:          []string{"framework", "spring", "annotation"},
	},
	{
		ID:            "spring_matrix_variable",
		Framework:     "spring",
		Language:      "java",
		Name:          "Spring @MatrixVariable",
		Description:   "Spring matrix variable annotation",
		MethodPattern: "^MatrixVariable$",
		SourceType:    common.SourceHTTPGet,
		PopulatedFrom: []string{"URL matrix parameters"},
		Confidence:    0.95,
		Tags:          []string{"framework", "spring", "annotation"},
	},
	{
		ID:            "spring_multipart_file",
		Framework:     "spring",
		Language:      "java",
		Name:          "Spring MultipartFile",
		Description:   "Spring multipart file upload",
		ClassPattern:  "^MultipartFile$",
		SourceType:    common.SourceHTTPFile,
		CarrierClass:  "MultipartFile",
		PopulatedFrom: []string{"uploaded file"},
		Confidence:    0.95,
		Tags:          []string{"framework", "spring"},
	},
}

// JAX-RS patterns (Jersey, RESTEasy, Quarkus)
var jaxrsPatterns = []*common.FrameworkPattern{
	{
		ID:            "jaxrs_query_param",
		Framework:     "jax-rs",
		Language:      "java",
		Name:          "JAX-RS @QueryParam",
		Description:   "JAX-RS query parameter annotation",
		MethodPattern: "^QueryParam$",
		SourceType:    common.SourceHTTPGet,
		PopulatedFrom: []string{"query string"},
		Confidence:    0.95,
		Tags:          []string{"framework", "jax-rs", "annotation"},
	},
	{
		ID:            "jaxrs_path_param",
		Framework:     "jax-rs",
		Language:      "java",
		Name:          "JAX-RS @PathParam",
		Description:   "JAX-RS path parameter annotation",
		MethodPattern: "^PathParam$",
		SourceType:    common.SourceHTTPPath,
		PopulatedFrom: []string{"URL path"},
		Confidence:    0.95,
		Tags:          []string{"framework", "jax-rs", "annotation"},
	},
	{
		ID:            "jaxrs_form_param",
		Framework:     "jax-rs",
		Language:      "java",
		Name:          "JAX-RS @FormParam",
		Description:   "JAX-RS form parameter annotation",
		MethodPattern: "^FormParam$",
		SourceType:    common.SourceHTTPPost,
		PopulatedFrom: []string{"form data"},
		Confidence:    0.95,
		Tags:          []string{"framework", "jax-rs", "annotation"},
	},
	{
		ID:            "jaxrs_header_param",
		Framework:     "jax-rs",
		Language:      "java",
		Name:          "JAX-RS @HeaderParam",
		Description:   "JAX-RS header parameter annotation",
		MethodPattern: "^HeaderParam$",
		SourceType:    common.SourceHTTPHeader,
		PopulatedFrom: []string{"HTTP headers"},
		Confidence:    0.95,
		Tags:          []string{"framework", "jax-rs", "annotation"},
	},
	{
		ID:            "jaxrs_cookie_param",
		Framework:     "jax-rs",
		Language:      "java",
		Name:          "JAX-RS @CookieParam",
		Description:   "JAX-RS cookie parameter annotation",
		MethodPattern: "^CookieParam$",
		SourceType:    common.SourceHTTPCookie,
		PopulatedFrom: []string{"cookies"},
		Confidence:    0.95,
		Tags:          []string{"framework", "jax-rs", "annotation"},
	},
	{
		ID:            "jaxrs_bean_param",
		Framework:     "jax-rs",
		Language:      "java",
		Name:          "JAX-RS @BeanParam",
		Description:   "JAX-RS bean parameter annotation",
		MethodPattern: "^BeanParam$",
		SourceType:    common.SourceUserInput,
		PopulatedFrom: []string{"multiple sources"},
		Confidence:    0.9,
		Tags:          []string{"framework", "jax-rs", "annotation"},
	},
	{
		ID:            "jaxrs_matrix_param",
		Framework:     "jax-rs",
		Language:      "java",
		Name:          "JAX-RS @MatrixParam",
		Description:   "JAX-RS matrix parameter annotation",
		MethodPattern: "^MatrixParam$",
		SourceType:    common.SourceHTTPGet,
		PopulatedFrom: []string{"URL matrix parameters"},
		Confidence:    0.95,
		Tags:          []string{"framework", "jax-rs", "annotation"},
	},
}

// Micronaut patterns
var micronautPatterns = []*common.FrameworkPattern{
	{
		ID:            "micronaut_query_value",
		Framework:     "micronaut",
		Language:      "java",
		Name:          "Micronaut @QueryValue",
		Description:   "Micronaut query value annotation",
		MethodPattern: "^QueryValue$",
		SourceType:    common.SourceHTTPGet,
		PopulatedFrom: []string{"query string"},
		Confidence:    0.95,
		Tags:          []string{"framework", "micronaut", "annotation"},
	},
	{
		ID:            "micronaut_path_value",
		Framework:     "micronaut",
		Language:      "java",
		Name:          "Micronaut @PathValue",
		Description:   "Micronaut path value annotation",
		MethodPattern: "^PathValue$",
		SourceType:    common.SourceHTTPPath,
		PopulatedFrom: []string{"URL path"},
		Confidence:    0.95,
		Tags:          []string{"framework", "micronaut", "annotation"},
	},
	{
		ID:            "micronaut_body",
		Framework:     "micronaut",
		Language:      "java",
		Name:          "Micronaut @Body",
		Description:   "Micronaut body annotation",
		MethodPattern: "^Body$",
		SourceType:    common.SourceHTTPBody,
		PopulatedFrom: []string{"HTTP body"},
		Confidence:    0.95,
		Tags:          []string{"framework", "micronaut", "annotation"},
	},
	{
		ID:            "micronaut_header",
		Framework:     "micronaut",
		Language:      "java",
		Name:          "Micronaut @Header",
		Description:   "Micronaut header annotation",
		MethodPattern: "^Header$",
		SourceType:    common.SourceHTTPHeader,
		PopulatedFrom: []string{"HTTP headers"},
		Confidence:    0.95,
		Tags:          []string{"framework", "micronaut", "annotation"},
	},
	{
		ID:            "micronaut_cookie_value",
		Framework:     "micronaut",
		Language:      "java",
		Name:          "Micronaut @CookieValue",
		Description:   "Micronaut cookie value annotation",
		MethodPattern: "^CookieValue$",
		SourceType:    common.SourceHTTPCookie,
		PopulatedFrom: []string{"cookies"},
		Confidence:    0.95,
		Tags:          []string{"framework", "micronaut", "annotation"},
	},
}

// Vert.x patterns
var vertxPatterns = []*common.FrameworkPattern{
	{
		ID:            "vertx_param",
		Framework:     "vertx",
		Language:      "java",
		Name:          "Vert.x @Param",
		Description:   "Vert.x parameter annotation",
		MethodPattern: "^Param$",
		SourceType:    common.SourceHTTPGet,
		PopulatedFrom: []string{"query string", "URL path"},
		Confidence:    0.9,
		Tags:          []string{"framework", "vertx", "annotation"},
	},
	{
		ID:            "vertx_request_param",
		Framework:     "vertx",
		Language:      "java",
		Name:          "Vert.x RoutingContext.request().getParam()",
		Description:   "Vert.x routing context parameter",
		MethodPattern: "^getParam$",
		SourceType:    common.SourceHTTPGet,
		PopulatedFrom: []string{"query string"},
		Confidence:    0.95,
		Tags:          []string{"framework", "vertx"},
	},
	{
		ID:            "vertx_body_as_json",
		Framework:     "vertx",
		Language:      "java",
		Name:          "Vert.x RoutingContext.body().asJsonObject()",
		Description:   "Vert.x routing context body as JSON",
		MethodPattern: "^asJsonObject$",
		SourceType:    common.SourceHTTPJSON,
		PopulatedFrom: []string{"JSON body"},
		Confidence:    0.95,
		Tags:          []string{"framework", "vertx"},
	},
}

// GetAllPatterns returns all registered framework patterns
func GetAllPatterns() []*common.FrameworkPattern {
	return Registry.GetAll()
}

// GetPatternsByFramework returns patterns for a specific framework
func GetPatternsByFramework(framework string) []*common.FrameworkPattern {
	return Registry.GetByFramework(framework)
}

// GetPatternByID returns a pattern by its ID
func GetPatternByID(id string) *common.FrameworkPattern {
	return Registry.GetByID(id)
}

func init() {
	// Register all patterns
	Registry.RegisterAll(servletPatterns)
	Registry.RegisterAll(springPatterns)
	Registry.RegisterAll(jaxrsPatterns)
	Registry.RegisterAll(micronautPatterns)
	Registry.RegisterAll(vertxPatterns)

	// Register framework detectors
	common.RegisterFrameworkDetector(&common.FrameworkDetector{
		Framework:  "spring",
		Indicators: []string{"pom.xml", "build.gradle", "spring-boot", "org.springframework"},
	})

	common.RegisterFrameworkDetector(&common.FrameworkDetector{
		Framework:  "jax-rs",
		Indicators: []string{"javax.ws.rs", "jakarta.ws.rs"},
	})

	common.RegisterFrameworkDetector(&common.FrameworkDetector{
		Framework:  "micronaut",
		Indicators: []string{"io.micronaut"},
	})

	common.RegisterFrameworkDetector(&common.FrameworkDetector{
		Framework:  "vertx",
		Indicators: []string{"io.vertx"},
	})
}
