// Package main - generator.go generates Go source files from parsed methods
package main

import (
	"fmt"
	"strings"
)

// Generator produces Go source code for framework patterns
type Generator struct {
	builder *strings.Builder
}

// NewGenerator creates a new code generator
func NewGenerator() *Generator {
	return &Generator{}
}

// GenerateLaravel generates laravel.go content
func (g *Generator) GenerateLaravel(methods []ParsedMethod, fw *FrameworkDefinition) string {
	g.builder = &strings.Builder{}

	g.writeHeader("https://github.com/illuminate/http")
	g.writePackage()
	g.writeImport()

	g.builder.WriteString("var laravelPatterns = []*common.FrameworkPattern{\n")

	for _, m := range methods {
		sourceType := InferSourceType(m.Name)
		populatedFrom := InferPopulatedFrom(sourceType)
		description := InferDescription(fw.Name, m.Name, false, sourceType)
		g.writePatternInferred(fw, m, sourceType, populatedFrom, description)
	}

	g.builder.WriteString("}\n\n")
	g.writeInit("laravel", fw)

	return g.builder.String()
}

// GenerateSymfony generates symfony.go content
func (g *Generator) GenerateSymfony(methods []ParsedMethod, properties []ParsedMethod, fw *FrameworkDefinition) string {
	g.builder = &strings.Builder{}

	g.writeHeader("https://github.com/symfony/http-foundation")
	g.writePackage()
	g.writeImport()

	g.builder.WriteString("var symfonyPatterns = []*common.FrameworkPattern{\n")

	// Properties still use explicit mapping
	for _, p := range properties {
		mapping := symfonyPropertyMappings()[p.Name]
		if mapping == nil {
			continue
		}
		g.writePropertyPattern(fw, p, mapping)
	}

	// Methods use inference
	for _, m := range methods {
		sourceType := InferSourceType(m.Name)
		populatedFrom := InferPopulatedFrom(sourceType)
		description := InferDescription(fw.Name, m.Name, false, sourceType)
		g.writeSymfonyMethodPatternInferred(fw, m, sourceType, populatedFrom, description)
	}

	g.builder.WriteString("}\n\n")
	g.writeInit("symfony", fw)

	return g.builder.String()
}

func (g *Generator) writeHeader(sourceURL string) {
	g.builder.WriteString("// Code generated by genpatterns. DO NOT EDIT.\n")
	g.builder.WriteString("// Source: " + sourceURL + "\n\n")
}

func (g *Generator) writePackage() {
	g.builder.WriteString("package php\n\n")
}

func (g *Generator) writeImport() {
	g.builder.WriteString("import (\n")
	g.builder.WriteString("\t\"github.com/hatlesswizard/inputtracer/pkg/sources/common\"\n")
	g.builder.WriteString(")\n\n")
}

func (g *Generator) writePropertyPattern(fw *FrameworkDefinition, p ParsedMethod, mapping *MethodMapping) {
	id := fmt.Sprintf("%s_request_%s", fw.Name, p.Name)
	name := fmt.Sprintf("%s $request->%s", capitalize(fw.Name), p.Name)

	g.builder.WriteString("\t{\n")
	fmt.Fprintf(g.builder, "\t\tID:              %q,\n", id)
	fmt.Fprintf(g.builder, "\t\tFramework:       %q,\n", fw.Name)
	fmt.Fprintf(g.builder, "\t\tLanguage:        %q,\n", fw.Language)
	fmt.Fprintf(g.builder, "\t\tName:            %q,\n", name)
	fmt.Fprintf(g.builder, "\t\tDescription:     %q,\n", mapping.Description)
	fmt.Fprintf(g.builder, "\t\tClassPattern:    %q,\n", fw.ClassPattern)
	fmt.Fprintf(g.builder, "\t\tPropertyPattern: \"^%s$\",\n", p.Name)
	fmt.Fprintf(g.builder, "\t\tSourceType:      common.%s,\n", mapping.SourceType)
	fmt.Fprintf(g.builder, "\t\tCarrierClass:    %q,\n", fw.CarrierClass)
	fmt.Fprintf(g.builder, "\t\tCarrierProperty: %q,\n", p.Name)
	if len(mapping.PopulatedFrom) > 0 {
		fmt.Fprintf(g.builder, "\t\tPopulatedFrom:   []string{%s},\n", g.formatStringSlice(mapping.PopulatedFrom))
	}
	fmt.Fprintf(g.builder, "\t\tTags:            []string{%s},\n", g.formatStringSlice(fw.Tags))
	g.builder.WriteString("\t},\n")
}

func (g *Generator) writePatternInferred(fw *FrameworkDefinition, m ParsedMethod, sourceType string, populatedFrom []string, description string) {
	id := fmt.Sprintf("%s_request_%s", fw.Name, m.Name)
	name := fmt.Sprintf("%s $request->%s()", capitalize(fw.Name), m.Name)

	g.builder.WriteString("\t{\n")
	fmt.Fprintf(g.builder, "\t\tID:            %q,\n", id)
	fmt.Fprintf(g.builder, "\t\tFramework:     %q,\n", fw.Name)
	fmt.Fprintf(g.builder, "\t\tLanguage:      %q,\n", fw.Language)
	fmt.Fprintf(g.builder, "\t\tName:          %q,\n", name)
	fmt.Fprintf(g.builder, "\t\tDescription:   %q,\n", description)
	fmt.Fprintf(g.builder, "\t\tClassPattern:  %q,\n", fw.ClassPattern)
	fmt.Fprintf(g.builder, "\t\tMethodPattern: \"^%s$\",\n", m.Name)
	fmt.Fprintf(g.builder, "\t\tSourceType:    common.%s,\n", sourceType)
	fmt.Fprintf(g.builder, "\t\tCarrierClass:  %q,\n", fw.CarrierClass)
	if len(populatedFrom) > 0 {
		fmt.Fprintf(g.builder, "\t\tPopulatedFrom: []string{%s},\n", g.formatStringSlice(populatedFrom))
	}
	fmt.Fprintf(g.builder, "\t\tTags:          []string{%s},\n", g.formatStringSlice(fw.Tags))
	g.builder.WriteString("\t},\n")
}

func (g *Generator) writeSymfonyMethodPatternInferred(fw *FrameworkDefinition, m ParsedMethod, sourceType string, populatedFrom []string, description string) {
	classPattern := "^(Symfony\\\\\\\\Component\\\\\\\\HttpFoundation\\\\\\\\)?ParameterBag$"
	id := fmt.Sprintf("%s_parameterbag_%s", fw.Name, m.Name)
	name := fmt.Sprintf("%s ParameterBag->%s()", capitalize(fw.Name), m.Name)

	g.builder.WriteString("\t{\n")
	fmt.Fprintf(g.builder, "\t\tID:            %q,\n", id)
	fmt.Fprintf(g.builder, "\t\tFramework:     %q,\n", fw.Name)
	fmt.Fprintf(g.builder, "\t\tLanguage:      %q,\n", fw.Language)
	fmt.Fprintf(g.builder, "\t\tName:          %q,\n", name)
	fmt.Fprintf(g.builder, "\t\tDescription:   %q,\n", description)
	fmt.Fprintf(g.builder, "\t\tClassPattern:  %q,\n", classPattern)
	fmt.Fprintf(g.builder, "\t\tMethodPattern: \"^%s$\",\n", m.Name)
	fmt.Fprintf(g.builder, "\t\tSourceType:    common.%s,\n", sourceType)
	if len(populatedFrom) > 0 {
		fmt.Fprintf(g.builder, "\t\tPopulatedFrom: []string{%s},\n", g.formatStringSlice(populatedFrom))
	}
	fmt.Fprintf(g.builder, "\t\tTags:          []string{%s},\n", g.formatStringSlice(fw.Tags))
	g.builder.WriteString("\t},\n")
}

func (g *Generator) writeInit(framework string, fw *FrameworkDefinition) {
	g.builder.WriteString("func init() {\n")
	fmt.Fprintf(g.builder, "\tRegistry.RegisterAll(%sPatterns)\n\n", framework)
	g.builder.WriteString("\t// Register framework detector\n")
	g.builder.WriteString("\tcommon.RegisterFrameworkDetector(&common.FrameworkDetector{\n")
	fmt.Fprintf(g.builder, "\t\tFramework:  %q,\n", framework)
	fmt.Fprintf(g.builder, "\t\tIndicators: []string{%s},\n", g.formatStringSlice(fw.FrameworkDetect))
	g.builder.WriteString("\t})\n")
	g.builder.WriteString("}\n")
}

// GenerateWordPress generates wordpress.go content
func (g *Generator) GenerateWordPress(methods []ParsedMethod, fw *FrameworkDefinition) string {
	g.builder = &strings.Builder{}

	g.writeHeader("https://github.com/WordPress/WordPress")
	g.writePackage()
	g.writeImport()

	g.builder.WriteString("var wordpressPatterns = []*common.FrameworkPattern{\n")

	for _, m := range methods {
		sourceType := InferWordPressSourceType(m.Name)
		populatedFrom := InferPopulatedFrom(sourceType)
		description := InferDescription(fw.Name, m.Name, false, sourceType)
		g.writeWordPressPattern(fw, m, sourceType, populatedFrom, description)
	}

	g.builder.WriteString("}\n\n")
	g.writeInit("wordpress", fw)

	return g.builder.String()
}

func (g *Generator) writeWordPressPattern(fw *FrameworkDefinition, m ParsedMethod, sourceType string, populatedFrom []string, description string) {
	id := fmt.Sprintf("%s_%s", fw.Name, m.Name)
	name := fmt.Sprintf("%s $request->%s()", "WordPress", m.Name)

	g.builder.WriteString("\t{\n")
	fmt.Fprintf(g.builder, "\t\tID:            %q,\n", id)
	fmt.Fprintf(g.builder, "\t\tFramework:     %q,\n", fw.Name)
	fmt.Fprintf(g.builder, "\t\tLanguage:      %q,\n", fw.Language)
	fmt.Fprintf(g.builder, "\t\tName:          %q,\n", name)
	fmt.Fprintf(g.builder, "\t\tDescription:   %q,\n", description)
	fmt.Fprintf(g.builder, "\t\tClassPattern:  %q,\n", fw.ClassPattern)
	fmt.Fprintf(g.builder, "\t\tMethodPattern: \"^%s$\",\n", m.Name)
	fmt.Fprintf(g.builder, "\t\tSourceType:    common.%s,\n", sourceType)
	fmt.Fprintf(g.builder, "\t\tCarrierClass:  %q,\n", fw.CarrierClass)
	if len(populatedFrom) > 0 {
		fmt.Fprintf(g.builder, "\t\tPopulatedFrom: []string{%s},\n", g.formatStringSlice(populatedFrom))
	}
	fmt.Fprintf(g.builder, "\t\tTags:          []string{%s},\n", g.formatStringSlice(fw.Tags))
	g.builder.WriteString("\t},\n")
}

func (g *Generator) formatStringSlice(s []string) string {
	quoted := make([]string, len(s))
	for i, v := range s {
		quoted[i] = fmt.Sprintf("%q", v)
	}
	return strings.Join(quoted, ", ")
}

// capitalize returns s with its first letter uppercased.
// Used in place of the deprecated strings.Title for single-word framework names.
func capitalize(s string) string {
	if s == "" {
		return ""
	}
	return strings.ToUpper(s[:1]) + s[1:]
}
