// Package javascript - express.go provides Express.js framework input patterns
package javascript

import (
	"github.com/hatlesswizard/inputtracer/pkg/sources/common"
)

var expressPatterns = []*common.FrameworkPattern{
	{
		ID:              "express_req_body",
		Framework:       "express",
		Language:        "javascript",
		Name:            "Express req.body",
		Description:     "Express request body, populated by body-parser middleware",
		PropertyPattern: "^body$",
		SourceType:      common.SourceHTTPBody,
		CarrierProperty: "body",
		PopulatedBy:     "body-parser",
		PopulatedFrom:   []string{"HTTP POST body"},
		Confidence:      0.95,
		Tags:            []string{"framework", "http", "post"},
	},
	{
		ID:              "express_req_query",
		Framework:       "express",
		Language:        "javascript",
		Name:            "Express req.query",
		Description:     "Express request query parameters",
		PropertyPattern: "^query$",
		SourceType:      common.SourceHTTPGet,
		CarrierProperty: "query",
		PopulatedBy:     "express",
		PopulatedFrom:   []string{"HTTP GET query string"},
		Confidence:      0.95,
		Tags:            []string{"framework", "http", "get"},
	},
	{
		ID:              "express_req_params",
		Framework:       "express",
		Language:        "javascript",
		Name:            "Express req.params",
		Description:     "Express route parameters from URL path",
		PropertyPattern: "^params$",
		SourceType:      common.SourceHTTPPath,
		CarrierProperty: "params",
		PopulatedBy:     "express-router",
		PopulatedFrom:   []string{"HTTP URL path"},
		Confidence:      0.95,
		Tags:            []string{"framework", "http", "path"},
	},
	{
		ID:              "express_req_headers",
		Framework:       "express",
		Language:        "javascript",
		Name:            "Express req.headers",
		Description:     "Express request headers",
		PropertyPattern: "^headers$",
		SourceType:      common.SourceHTTPHeader,
		CarrierProperty: "headers",
		PopulatedBy:     "http",
		PopulatedFrom:   []string{"HTTP headers"},
		Confidence:      0.95,
		Tags:            []string{"framework", "http", "header"},
	},
	{
		ID:              "express_req_cookies",
		Framework:       "express",
		Language:        "javascript",
		Name:            "Express req.cookies",
		Description:     "Express request cookies, populated by cookie-parser middleware",
		PropertyPattern: "^cookies$",
		SourceType:      common.SourceHTTPCookie,
		CarrierProperty: "cookies",
		PopulatedBy:     "cookie-parser",
		PopulatedFrom:   []string{"HTTP Cookie header"},
		Confidence:      0.95,
		Tags:            []string{"framework", "http", "cookie"},
	},
	{
		ID:              "express_req_signedcookies",
		Framework:       "express",
		Language:        "javascript",
		Name:            "Express req.signedCookies",
		Description:     "Express signed cookies, populated by cookie-parser middleware",
		PropertyPattern: "^signedCookies$",
		SourceType:      common.SourceHTTPCookie,
		CarrierProperty: "signedCookies",
		PopulatedBy:     "cookie-parser",
		PopulatedFrom:   []string{"HTTP Cookie header"},
		Confidence:      0.95,
		Tags:            []string{"framework", "http", "cookie"},
	},
	{
		ID:            "express_req_get",
		Framework:     "express",
		Language:      "javascript",
		Name:          "Express req.get()",
		Description:   "Express method to get a header value",
		MethodPattern: "^get$",
		SourceType:    common.SourceHTTPHeader,
		PopulatedFrom: []string{"HTTP headers"},
		Confidence:    0.9,
		Tags:          []string{"framework", "http", "header"},
	},
	{
		ID:            "express_req_header",
		Framework:     "express",
		Language:      "javascript",
		Name:          "Express req.header()",
		Description:   "Express method to get a header value (alias for get)",
		MethodPattern: "^header$",
		SourceType:    common.SourceHTTPHeader,
		PopulatedFrom: []string{"HTTP headers"},
		Confidence:    0.9,
		Tags:          []string{"framework", "http", "header"},
	},
	{
		ID:            "express_req_param",
		Framework:     "express",
		Language:      "javascript",
		Name:          "Express req.param()",
		Description:   "Express method to get a parameter from body, query, or params",
		MethodPattern: "^param$",
		SourceType:    common.SourceUserInput,
		PopulatedFrom: []string{"HTTP body", "query string", "URL path"},
		Confidence:    0.95,
		Tags:          []string{"framework", "http"},
	},
	{
		ID:              "express_req_files",
		Framework:       "express",
		Language:        "javascript",
		Name:            "Express req.files",
		Description:     "Express uploaded files, populated by multer or similar middleware",
		PropertyPattern: "^files$",
		SourceType:      common.SourceHTTPFile,
		CarrierProperty: "files",
		PopulatedBy:     "multer",
		PopulatedFrom:   []string{"HTTP multipart form data"},
		Confidence:      0.95,
		Tags:            []string{"framework", "http", "file"},
	},
	{
		ID:              "express_req_file",
		Framework:       "express",
		Language:        "javascript",
		Name:            "Express req.file",
		Description:     "Express single uploaded file, populated by multer",
		PropertyPattern: "^file$",
		SourceType:      common.SourceHTTPFile,
		CarrierProperty: "file",
		PopulatedBy:     "multer",
		PopulatedFrom:   []string{"HTTP multipart form data"},
		Confidence:      0.95,
		Tags:            []string{"framework", "http", "file"},
	},
	{
		ID:              "express_req_hostname",
		Framework:       "express",
		Language:        "javascript",
		Name:            "Express req.hostname",
		Description:     "Express request hostname from Host header",
		PropertyPattern: "^hostname$",
		SourceType:      common.SourceHTTPHeader,
		PopulatedFrom:   []string{"HTTP Host header"},
		Confidence:      0.85,
		Tags:            []string{"framework", "http", "header"},
	},
	{
		ID:              "express_req_ip",
		Framework:       "express",
		Language:        "javascript",
		Name:            "Express req.ip",
		Description:     "Express remote IP address",
		PropertyPattern: "^ip$",
		SourceType:      common.SourceNetwork,
		PopulatedFrom:   []string{"TCP connection", "X-Forwarded-For header"},
		Confidence:      0.8,
		Tags:            []string{"framework", "network"},
	},
	{
		ID:              "express_req_path",
		Framework:       "express",
		Language:        "javascript",
		Name:            "Express req.path",
		Description:     "Express request path",
		PropertyPattern: "^path$",
		SourceType:      common.SourceHTTPPath,
		PopulatedFrom:   []string{"HTTP URL path"},
		Confidence:      0.9,
		Tags:            []string{"framework", "http", "path"},
	},
	{
		ID:              "express_req_url",
		Framework:       "express",
		Language:        "javascript",
		Name:            "Express req.url",
		Description:     "Express request URL",
		PropertyPattern: "^url$",
		SourceType:      common.SourceUserInput,
		PopulatedFrom:   []string{"HTTP request URL"},
		Confidence:      0.9,
		Tags:            []string{"framework", "http"},
	},
	{
		ID:              "express_req_originalurl",
		Framework:       "express",
		Language:        "javascript",
		Name:            "Express req.originalUrl",
		Description:     "Express original request URL before rewrites",
		PropertyPattern: "^originalUrl$",
		SourceType:      common.SourceUserInput,
		PopulatedFrom:   []string{"HTTP request URL"},
		Confidence:      0.9,
		Tags:            []string{"framework", "http"},
	},
	{
		ID:              "express_req_session",
		Framework:       "express",
		Language:        "javascript",
		Name:            "Express req.session",
		Description:     "Express session data, populated by express-session",
		PropertyPattern: "^session$",
		SourceType:      common.SourceSession,
		CarrierProperty: "session",
		PopulatedBy:     "express-session",
		PopulatedFrom:   []string{"Session storage"},
		Confidence:      0.7, // Session data may contain user input
		Tags:            []string{"framework", "session"},
	},
}

func init() {
	Registry.RegisterAll(expressPatterns)

	// Register Express framework detector
	common.RegisterFrameworkDetector(&common.FrameworkDetector{
		Framework:  "express",
		Indicators: []string{"app.js", "server.js", "routes/", "middleware/"},
	})
}
