// Package javascript - fastify.go provides Fastify framework input patterns
package javascript

import (
	"github.com/hatlesswizard/inputtracer/pkg/sources/common"
)

var fastifyPatterns = []*common.FrameworkPattern{
	// request object patterns
	{
		ID:              "fastify_request_body",
		Framework:       "fastify",
		Language:        "javascript",
		Name:            "Fastify request.body",
		Description:     "Fastify request body (automatically parsed)",
		PropertyPattern: "^body$",
		SourceType:      common.SourceHTTPBody,
		CarrierProperty: "body",
		PopulatedBy:     "fastify",
		PopulatedFrom:   []string{"HTTP POST body"},
		Confidence:      0.95,
		Tags:            []string{"framework", "http", "post"},
	},
	{
		ID:              "fastify_request_query",
		Framework:       "fastify",
		Language:        "javascript",
		Name:            "Fastify request.query",
		Description:     "Fastify request query parameters",
		PropertyPattern: "^query$",
		SourceType:      common.SourceHTTPGet,
		CarrierProperty: "query",
		PopulatedFrom:   []string{"HTTP GET query string"},
		Confidence:      0.95,
		Tags:            []string{"framework", "http", "get"},
	},
	{
		ID:              "fastify_request_params",
		Framework:       "fastify",
		Language:        "javascript",
		Name:            "Fastify request.params",
		Description:     "Fastify route parameters from URL path",
		PropertyPattern: "^params$",
		SourceType:      common.SourceHTTPPath,
		CarrierProperty: "params",
		PopulatedFrom:   []string{"HTTP URL path"},
		Confidence:      0.95,
		Tags:            []string{"framework", "http", "path"},
	},
	{
		ID:              "fastify_request_headers",
		Framework:       "fastify",
		Language:        "javascript",
		Name:            "Fastify request.headers",
		Description:     "Fastify request headers",
		PropertyPattern: "^headers$",
		SourceType:      common.SourceHTTPHeader,
		CarrierProperty: "headers",
		PopulatedFrom:   []string{"HTTP headers"},
		Confidence:      0.95,
		Tags:            []string{"framework", "http", "header"},
	},
	{
		ID:              "fastify_request_raw",
		Framework:       "fastify",
		Language:        "javascript",
		Name:            "Fastify request.raw",
		Description:     "Fastify raw Node.js IncomingMessage",
		PropertyPattern: "^raw$",
		SourceType:      common.SourceHTTPBody,
		PopulatedFrom:   []string{"HTTP request"},
		Confidence:      0.8,
		Tags:            []string{"framework", "http"},
	},
	// URL and routing
	{
		ID:              "fastify_request_url",
		Framework:       "fastify",
		Language:        "javascript",
		Name:            "Fastify request.url",
		Description:     "Fastify request URL",
		PropertyPattern: "^url$",
		SourceType:      common.SourceUserInput,
		PopulatedFrom:   []string{"HTTP request URL"},
		Confidence:      0.9,
		Tags:            []string{"framework", "http"},
	},
	{
		ID:              "fastify_request_routerpath",
		Framework:       "fastify",
		Language:        "javascript",
		Name:            "Fastify request.routerPath",
		Description:     "Fastify matched route path",
		PropertyPattern: "^routerPath$",
		SourceType:      common.SourceHTTPPath,
		PopulatedFrom:   []string{"HTTP URL path"},
		Confidence:      0.85,
		Tags:            []string{"framework", "http", "path"},
	},
	// IP and connection
	{
		ID:              "fastify_request_ip",
		Framework:       "fastify",
		Language:        "javascript",
		Name:            "Fastify request.ip",
		Description:     "Fastify remote IP address",
		PropertyPattern: "^ip$",
		SourceType:      common.SourceNetwork,
		PopulatedFrom:   []string{"TCP connection", "X-Forwarded-For header"},
		Confidence:      0.8,
		Tags:            []string{"framework", "network"},
	},
	{
		ID:              "fastify_request_ips",
		Framework:       "fastify",
		Language:        "javascript",
		Name:            "Fastify request.ips",
		Description:     "Fastify IP addresses from X-Forwarded-For",
		PropertyPattern: "^ips$",
		SourceType:      common.SourceHTTPHeader,
		PopulatedFrom:   []string{"X-Forwarded-For header"},
		Confidence:      0.8,
		Tags:            []string{"framework", "http", "header"},
	},
	{
		ID:              "fastify_request_hostname",
		Framework:       "fastify",
		Language:        "javascript",
		Name:            "Fastify request.hostname",
		Description:     "Fastify hostname from Host header",
		PropertyPattern: "^hostname$",
		SourceType:      common.SourceHTTPHeader,
		PopulatedFrom:   []string{"HTTP Host header"},
		Confidence:      0.85,
		Tags:            []string{"framework", "http", "header"},
	},
	// Cookie patterns (with @fastify/cookie)
	{
		ID:              "fastify_request_cookies",
		Framework:       "fastify",
		Language:        "javascript",
		Name:            "Fastify request.cookies",
		Description:     "Fastify cookies, populated by @fastify/cookie",
		PropertyPattern: "^cookies$",
		SourceType:      common.SourceHTTPCookie,
		CarrierProperty: "cookies",
		PopulatedBy:     "@fastify/cookie",
		PopulatedFrom:   []string{"HTTP Cookie header"},
		Confidence:      0.95,
		Tags:            []string{"framework", "http", "cookie"},
	},
	// Session patterns (with @fastify/session)
	{
		ID:              "fastify_request_session",
		Framework:       "fastify",
		Language:        "javascript",
		Name:            "Fastify request.session",
		Description:     "Fastify session data, populated by @fastify/session",
		PropertyPattern: "^session$",
		SourceType:      common.SourceSession,
		CarrierProperty: "session",
		PopulatedBy:     "@fastify/session",
		PopulatedFrom:   []string{"Session storage"},
		Confidence:      0.7,
		Tags:            []string{"framework", "session"},
	},
	// File upload patterns (with @fastify/multipart)
	{
		ID:            "fastify_request_file",
		Framework:     "fastify",
		Language:      "javascript",
		Name:          "Fastify request.file()",
		Description:   "Fastify single file upload, populated by @fastify/multipart",
		MethodPattern: "^file$",
		SourceType:    common.SourceHTTPFile,
		PopulatedBy:   "@fastify/multipart",
		PopulatedFrom: []string{"HTTP multipart form data"},
		Confidence:    0.95,
		Tags:          []string{"framework", "http", "file"},
	},
	{
		ID:            "fastify_request_files",
		Framework:     "fastify",
		Language:      "javascript",
		Name:          "Fastify request.files()",
		Description:   "Fastify multiple file uploads, populated by @fastify/multipart",
		MethodPattern: "^files$",
		SourceType:    common.SourceHTTPFile,
		PopulatedBy:   "@fastify/multipart",
		PopulatedFrom: []string{"HTTP multipart form data"},
		Confidence:    0.95,
		Tags:          []string{"framework", "http", "file"},
	},
	{
		ID:            "fastify_request_parts",
		Framework:     "fastify",
		Language:      "javascript",
		Name:          "Fastify request.parts()",
		Description:   "Fastify multipart parts iterator, populated by @fastify/multipart",
		MethodPattern: "^parts$",
		SourceType:    common.SourceHTTPFile,
		PopulatedBy:   "@fastify/multipart",
		PopulatedFrom: []string{"HTTP multipart form data"},
		Confidence:    0.95,
		Tags:          []string{"framework", "http", "file"},
	},
	// JWT patterns (with @fastify/jwt)
	{
		ID:              "fastify_request_user",
		Framework:       "fastify",
		Language:        "javascript",
		Name:            "Fastify request.user",
		Description:     "Fastify user from JWT token, populated by @fastify/jwt",
		PropertyPattern: "^user$",
		SourceType:      common.SourceHTTPHeader,
		PopulatedBy:     "@fastify/jwt",
		PopulatedFrom:   []string{"Authorization header (JWT)"},
		Confidence:      0.8,
		Tags:            []string{"framework", "auth"},
	},
	// Validation patterns (input that passed validation)
	{
		ID:              "fastify_request_validateddata",
		Framework:       "fastify",
		Language:        "javascript",
		Name:            "Fastify validated data",
		Description:     "Fastify validated request data (body, query, params)",
		PropertyPattern: "^validatedData$",
		SourceType:      common.SourceUserInput,
		PopulatedFrom:   []string{"HTTP body", "query string", "URL path"},
		Confidence:      0.85, // Validated but still user input
		Tags:            []string{"framework", "validated"},
	},
}

// Hapi.js patterns (additional HTTP framework)
var hapiPatterns = []*common.FrameworkPattern{
	{
		ID:              "hapi_request_payload",
		Framework:       "hapi",
		Language:        "javascript",
		Name:            "Hapi request.payload",
		Description:     "Hapi request payload (body)",
		PropertyPattern: "^payload$",
		SourceType:      common.SourceHTTPBody,
		CarrierProperty: "payload",
		PopulatedFrom:   []string{"HTTP POST body"},
		Confidence:      0.95,
		Tags:            []string{"framework", "http", "post"},
	},
	{
		ID:              "hapi_request_query",
		Framework:       "hapi",
		Language:        "javascript",
		Name:            "Hapi request.query",
		Description:     "Hapi request query parameters",
		PropertyPattern: "^query$",
		SourceType:      common.SourceHTTPGet,
		CarrierProperty: "query",
		PopulatedFrom:   []string{"HTTP GET query string"},
		Confidence:      0.95,
		Tags:            []string{"framework", "http", "get"},
	},
	{
		ID:              "hapi_request_params",
		Framework:       "hapi",
		Language:        "javascript",
		Name:            "Hapi request.params",
		Description:     "Hapi route parameters",
		PropertyPattern: "^params$",
		SourceType:      common.SourceHTTPPath,
		CarrierProperty: "params",
		PopulatedFrom:   []string{"HTTP URL path"},
		Confidence:      0.95,
		Tags:            []string{"framework", "http", "path"},
	},
	{
		ID:              "hapi_request_headers",
		Framework:       "hapi",
		Language:        "javascript",
		Name:            "Hapi request.headers",
		Description:     "Hapi request headers",
		PropertyPattern: "^headers$",
		SourceType:      common.SourceHTTPHeader,
		CarrierProperty: "headers",
		PopulatedFrom:   []string{"HTTP headers"},
		Confidence:      0.95,
		Tags:            []string{"framework", "http", "header"},
	},
	{
		ID:              "hapi_request_state",
		Framework:       "hapi",
		Language:        "javascript",
		Name:            "Hapi request.state",
		Description:     "Hapi cookies (state)",
		PropertyPattern: "^state$",
		SourceType:      common.SourceHTTPCookie,
		CarrierProperty: "state",
		PopulatedFrom:   []string{"HTTP Cookie header"},
		Confidence:      0.95,
		Tags:            []string{"framework", "http", "cookie"},
	},
	{
		ID:              "hapi_request_path",
		Framework:       "hapi",
		Language:        "javascript",
		Name:            "Hapi request.path",
		Description:     "Hapi request path",
		PropertyPattern: "^path$",
		SourceType:      common.SourceHTTPPath,
		PopulatedFrom:   []string{"HTTP URL path"},
		Confidence:      0.9,
		Tags:            []string{"framework", "http", "path"},
	},
	{
		ID:              "hapi_request_url",
		Framework:       "hapi",
		Language:        "javascript",
		Name:            "Hapi request.url",
		Description:     "Hapi request URL object",
		PropertyPattern: "^url$",
		SourceType:      common.SourceUserInput,
		PopulatedFrom:   []string{"HTTP request URL"},
		Confidence:      0.9,
		Tags:            []string{"framework", "http"},
	},
}

func init() {
	Registry.RegisterAll(fastifyPatterns)
	Registry.RegisterAll(hapiPatterns)

	// Register Fastify framework detector
	common.RegisterFrameworkDetector(&common.FrameworkDetector{
		Framework:  "fastify",
		Indicators: []string{"app.js", "server.js", "routes/", "plugins/"},
	})

	// Register Hapi framework detector
	common.RegisterFrameworkDetector(&common.FrameworkDetector{
		Framework:  "hapi",
		Indicators: []string{"server.js", "routes/", "plugins/"},
	})
}
