// Package javascript - koa.go provides Koa.js framework input patterns
package javascript

import (
	"github.com/hatlesswizard/inputtracer/pkg/sources/common"
)

var koaPatterns = []*common.FrameworkPattern{
	// ctx.request patterns
	{
		ID:              "koa_ctx_request_body",
		Framework:       "koa",
		Language:        "javascript",
		Name:            "Koa ctx.request.body",
		Description:     "Koa request body, populated by koa-bodyparser",
		PropertyPattern: "^body$",
		SourceType:      common.SourceHTTPBody,
		CarrierProperty: "body",
		PopulatedBy:     "koa-bodyparser",
		PopulatedFrom:   []string{"HTTP POST body"},
		Tags:            []string{"framework", "http", "post"},
	},
	{
		ID:              "koa_ctx_request_query",
		Framework:       "koa",
		Language:        "javascript",
		Name:            "Koa ctx.request.query",
		Description:     "Koa request query parameters (alias on request object)",
		PropertyPattern: "^query$",
		SourceType:      common.SourceHTTPGet,
		CarrierProperty: "query",
		PopulatedFrom:   []string{"HTTP GET query string"},
		Tags:            []string{"framework", "http", "get"},
	},
	{
		ID:              "koa_ctx_request_querystring",
		Framework:       "koa",
		Language:        "javascript",
		Name:            "Koa ctx.request.querystring",
		Description:     "Koa raw query string",
		PropertyPattern: "^querystring$",
		SourceType:      common.SourceHTTPGet,
		PopulatedFrom:   []string{"HTTP GET query string"},
		Tags:            []string{"framework", "http", "get"},
	},
	{
		ID:              "koa_ctx_request_header",
		Framework:       "koa",
		Language:        "javascript",
		Name:            "Koa ctx.request.header",
		Description:     "Koa request headers object",
		PropertyPattern: "^header$",
		SourceType:      common.SourceHTTPHeader,
		CarrierProperty: "header",
		PopulatedFrom:   []string{"HTTP headers"},
		Tags:            []string{"framework", "http", "header"},
	},
	{
		ID:              "koa_ctx_request_headers",
		Framework:       "koa",
		Language:        "javascript",
		Name:            "Koa ctx.request.headers",
		Description:     "Koa request headers object (alias)",
		PropertyPattern: "^headers$",
		SourceType:      common.SourceHTTPHeader,
		CarrierProperty: "headers",
		PopulatedFrom:   []string{"HTTP headers"},
		Tags:            []string{"framework", "http", "header"},
	},
	// ctx shortcuts (delegated from ctx.request)
	{
		ID:              "koa_ctx_query",
		Framework:       "koa",
		Language:        "javascript",
		Name:            "Koa ctx.query",
		Description:     "Koa query parameters (shortcut for ctx.request.query)",
		PropertyPattern: "^query$",
		SourceType:      common.SourceHTTPGet,
		CarrierProperty: "query",
		PopulatedFrom:   []string{"HTTP GET query string"},
		Tags:            []string{"framework", "http", "get"},
	},
	{
		ID:              "koa_ctx_querystring",
		Framework:       "koa",
		Language:        "javascript",
		Name:            "Koa ctx.querystring",
		Description:     "Koa raw query string (shortcut for ctx.request.querystring)",
		PropertyPattern: "^querystring$",
		SourceType:      common.SourceHTTPGet,
		PopulatedFrom:   []string{"HTTP GET query string"},
		Tags:            []string{"framework", "http", "get"},
	},
	{
		ID:              "koa_ctx_header",
		Framework:       "koa",
		Language:        "javascript",
		Name:            "Koa ctx.header",
		Description:     "Koa headers (shortcut for ctx.request.header)",
		PropertyPattern: "^header$",
		SourceType:      common.SourceHTTPHeader,
		CarrierProperty: "header",
		PopulatedFrom:   []string{"HTTP headers"},
		Tags:            []string{"framework", "http", "header"},
	},
	{
		ID:              "koa_ctx_headers",
		Framework:       "koa",
		Language:        "javascript",
		Name:            "Koa ctx.headers",
		Description:     "Koa headers (shortcut for ctx.request.headers)",
		PropertyPattern: "^headers$",
		SourceType:      common.SourceHTTPHeader,
		CarrierProperty: "headers",
		PopulatedFrom:   []string{"HTTP headers"},
		Tags:            []string{"framework", "http", "header"},
	},
	// koa-router params
	{
		ID:              "koa_ctx_params",
		Framework:       "koa",
		Language:        "javascript",
		Name:            "Koa ctx.params",
		Description:     "Koa route parameters, populated by @koa/router",
		PropertyPattern: "^params$",
		SourceType:      common.SourceHTTPPath,
		CarrierProperty: "params",
		PopulatedBy:     "@koa/router",
		PopulatedFrom:   []string{"HTTP URL path"},
		Tags:            []string{"framework", "http", "path"},
	},
	// Cookie patterns
	{
		ID:              "koa_ctx_cookies",
		Framework:       "koa",
		Language:        "javascript",
		Name:            "Koa ctx.cookies",
		Description:     "Koa cookies manager",
		PropertyPattern: "^cookies$",
		SourceType:      common.SourceHTTPCookie,
		CarrierProperty: "cookies",
		PopulatedFrom:   []string{"HTTP Cookie header"},
		Tags:            []string{"framework", "http", "cookie"},
	},
	{
		ID:            "koa_cookies_get",
		Framework:     "koa",
		Language:      "javascript",
		Name:          "Koa ctx.cookies.get()",
		Description:   "Koa method to get a cookie value",
		MethodPattern: "^get$",
		SourceType:    common.SourceHTTPCookie,
		PopulatedFrom: []string{"HTTP Cookie header"},
		Tags:          []string{"framework", "http", "cookie"},
	},
	// URL and path patterns
	{
		ID:              "koa_ctx_url",
		Framework:       "koa",
		Language:        "javascript",
		Name:            "Koa ctx.url",
		Description:     "Koa request URL",
		PropertyPattern: "^url$",
		SourceType:      common.SourceUserInput,
		PopulatedFrom:   []string{"HTTP request URL"},
		Tags:            []string{"framework", "http"},
	},
	{
		ID:              "koa_ctx_originalurl",
		Framework:       "koa",
		Language:        "javascript",
		Name:            "Koa ctx.originalUrl",
		Description:     "Koa original request URL",
		PropertyPattern: "^originalUrl$",
		SourceType:      common.SourceUserInput,
		PopulatedFrom:   []string{"HTTP request URL"},
		Tags:            []string{"framework", "http"},
	},
	{
		ID:              "koa_ctx_path",
		Framework:       "koa",
		Language:        "javascript",
		Name:            "Koa ctx.path",
		Description:     "Koa request path",
		PropertyPattern: "^path$",
		SourceType:      common.SourceHTTPPath,
		PopulatedFrom:   []string{"HTTP URL path"},
		Tags:            []string{"framework", "http", "path"},
	},
	{
		ID:              "koa_ctx_href",
		Framework:       "koa",
		Language:        "javascript",
		Name:            "Koa ctx.href",
		Description:     "Koa full request URL",
		PropertyPattern: "^href$",
		SourceType:      common.SourceUserInput,
		PopulatedFrom:   []string{"HTTP request URL"},
		Tags:            []string{"framework", "http"},
	},
	// Header access methods
	{
		ID:            "koa_ctx_get",
		Framework:     "koa",
		Language:      "javascript",
		Name:          "Koa ctx.get()",
		Description:   "Koa method to get a header value",
		MethodPattern: "^get$",
		SourceType:    common.SourceHTTPHeader,
		PopulatedFrom: []string{"HTTP headers"},
		Tags:          []string{"framework", "http", "header"},
	},
	// Host and IP
	{
		ID:              "koa_ctx_host",
		Framework:       "koa",
		Language:        "javascript",
		Name:            "Koa ctx.host",
		Description:     "Koa host from Host header",
		PropertyPattern: "^host$",
		SourceType:      common.SourceHTTPHeader,
		PopulatedFrom:   []string{"HTTP Host header"},
		Tags:            []string{"framework", "http", "header"},
	},
	{
		ID:              "koa_ctx_hostname",
		Framework:       "koa",
		Language:        "javascript",
		Name:            "Koa ctx.hostname",
		Description:     "Koa hostname from Host header (without port)",
		PropertyPattern: "^hostname$",
		SourceType:      common.SourceHTTPHeader,
		PopulatedFrom:   []string{"HTTP Host header"},
		Tags:            []string{"framework", "http", "header"},
	},
	{
		ID:              "koa_ctx_ip",
		Framework:       "koa",
		Language:        "javascript",
		Name:            "Koa ctx.ip",
		Description:     "Koa remote IP address",
		PropertyPattern: "^ip$",
		SourceType:      common.SourceNetwork,
		PopulatedFrom:   []string{"TCP connection", "X-Forwarded-For header"},
		Tags:            []string{"framework", "network"},
	},
	{
		ID:              "koa_ctx_ips",
		Framework:       "koa",
		Language:        "javascript",
		Name:            "Koa ctx.ips",
		Description:     "Koa IP addresses from X-Forwarded-For",
		PropertyPattern: "^ips$",
		SourceType:      common.SourceHTTPHeader,
		PopulatedFrom:   []string{"X-Forwarded-For header"},
		Tags:            []string{"framework", "http", "header"},
	},
	// File upload with koa-body or similar
	{
		ID:              "koa_ctx_request_files",
		Framework:       "koa",
		Language:        "javascript",
		Name:            "Koa ctx.request.files",
		Description:     "Koa uploaded files, populated by koa-body",
		PropertyPattern: "^files$",
		SourceType:      common.SourceHTTPFile,
		CarrierProperty: "files",
		PopulatedBy:     "koa-body",
		PopulatedFrom:   []string{"HTTP multipart form data"},
		Tags:            []string{"framework", "http", "file"},
	},
	// State (may contain user input)
	{
		ID:              "koa_ctx_state",
		Framework:       "koa",
		Language:        "javascript",
		Name:            "Koa ctx.state",
		Description:     "Koa context state object (may contain user-derived data)",
		PropertyPattern: "^state$",
		SourceType:      common.SourceUserInput,
		Tags:            []string{"framework"},
	},
}

func init() {
	Registry.RegisterAll(koaPatterns)

	// Register Koa framework detector
	common.RegisterFrameworkDetector(&common.FrameworkDetector{
		Framework:  "koa",
		Indicators: []string{"app.js", "server.js", "routes/", "middleware/"},
	})
}
