// Package c - input_patterns.go provides C-specific input source patterns
// These patterns identify where user input enters C programs
package c

import (
	"github.com/hatlesswizard/inputtracer/pkg/sources/common"
)

// Registry is the global C input pattern registry
var Registry = common.NewFrameworkPatternRegistry("c")

// CGI environment variable patterns for web CGI programs
var cgiPatterns = []*common.FrameworkPattern{
	{
		ID:             "c_cgi_query_string",
		Framework:      "cgi",
		Language:       "c",
		Name:           "QUERY_STRING",
		Description:    "CGI query string environment variable",
		PropertyPattern: "^QUERY_STRING$",
		SourceType:     common.SourceHTTPGet,
		Confidence:     1.0,
		Tags:           []string{"cgi", "web", "legacy"},
	},
	{
		ID:             "c_cgi_content_length",
		Framework:      "cgi",
		Language:       "c",
		Name:           "CONTENT_LENGTH",
		Description:    "CGI content length environment variable",
		PropertyPattern: "^CONTENT_LENGTH$",
		SourceType:     common.SourceHTTPBody,
		Confidence:     1.0,
		Tags:           []string{"cgi", "web", "legacy"},
	},
	{
		ID:             "c_cgi_content_type",
		Framework:      "cgi",
		Language:       "c",
		Name:           "CONTENT_TYPE",
		Description:    "CGI content type environment variable",
		PropertyPattern: "^CONTENT_TYPE$",
		SourceType:     common.SourceHTTPHeader,
		Confidence:     1.0,
		Tags:           []string{"cgi", "web", "legacy"},
	},
	{
		ID:             "c_cgi_http_cookie",
		Framework:      "cgi",
		Language:       "c",
		Name:           "HTTP_COOKIE",
		Description:    "CGI HTTP cookie environment variable",
		PropertyPattern: "^HTTP_COOKIE$",
		SourceType:     common.SourceHTTPCookie,
		Confidence:     1.0,
		Tags:           []string{"cgi", "web", "legacy"},
	},
	{
		ID:             "c_cgi_request_method",
		Framework:      "cgi",
		Language:       "c",
		Name:           "REQUEST_METHOD",
		Description:    "CGI request method environment variable",
		PropertyPattern: "^REQUEST_METHOD$",
		SourceType:     common.SourceHTTPHeader,
		Confidence:     1.0,
		Tags:           []string{"cgi", "web", "legacy"},
	},
	{
		ID:             "c_cgi_path_info",
		Framework:      "cgi",
		Language:       "c",
		Name:           "PATH_INFO",
		Description:    "CGI path info environment variable",
		PropertyPattern: "^PATH_INFO$",
		SourceType:     common.SourceHTTPPath,
		Confidence:     1.0,
		Tags:           []string{"cgi", "web", "legacy"},
	},
	{
		ID:             "c_cgi_remote_addr",
		Framework:      "cgi",
		Language:       "c",
		Name:           "REMOTE_ADDR",
		Description:    "CGI remote address environment variable",
		PropertyPattern: "^REMOTE_ADDR$",
		SourceType:     common.SourceNetwork,
		Confidence:     1.0,
		Tags:           []string{"cgi", "web", "legacy"},
	},
	{
		ID:             "c_cgi_http_user_agent",
		Framework:      "cgi",
		Language:       "c",
		Name:           "HTTP_USER_AGENT",
		Description:    "CGI user agent environment variable",
		PropertyPattern: "^HTTP_USER_AGENT$",
		SourceType:     common.SourceHTTPHeader,
		Confidence:     1.0,
		Tags:           []string{"cgi", "web", "legacy"},
	},
	{
		ID:             "c_cgi_http_referer",
		Framework:      "cgi",
		Language:       "c",
		Name:           "HTTP_REFERER",
		Description:    "CGI referer environment variable",
		PropertyPattern: "^HTTP_REFERER$",
		SourceType:     common.SourceHTTPHeader,
		Confidence:     1.0,
		Tags:           []string{"cgi", "web", "legacy"},
	},
	{
		ID:             "c_cgi_http_host",
		Framework:      "cgi",
		Language:       "c",
		Name:           "HTTP_HOST",
		Description:    "CGI host environment variable",
		PropertyPattern: "^HTTP_HOST$",
		SourceType:     common.SourceHTTPHeader,
		Confidence:     1.0,
		Tags:           []string{"cgi", "web", "legacy"},
	},
}

// Core C input patterns for CLI and standard I/O
var corePatterns = []*common.FrameworkPattern{
	{
		ID:            "c_argv",
		Framework:     "core",
		Language:      "c",
		Name:          "argv[]",
		Description:   "Command line arguments array",
		PropertyPattern: "^argv$",
		SourceType:   common.SourceCLIArg,
		Confidence:   1.0,
		Tags:         []string{"cli", "core"},
	},
	{
		ID:            "c_argc",
		Framework:     "core",
		Language:      "c",
		Name:          "argc",
		Description:   "Command line argument count",
		PropertyPattern: "^argc$",
		SourceType:   common.SourceCLIArg,
		Confidence:   1.0,
		Tags:         []string{"cli", "core"},
	},
	{
		ID:            "c_envp",
		Framework:     "core",
		Language:      "c",
		Name:          "envp[]",
		Description:   "Environment variables array (main parameter)",
		PropertyPattern: "^envp$",
		SourceType:   common.SourceEnvVar,
		Confidence:   1.0,
		Tags:         []string{"environment", "core"},
	},
	{
		ID:            "c_environ",
		Framework:     "core",
		Language:      "c",
		Name:          "environ",
		Description:   "Global environment variables array",
		PropertyPattern: "^environ$",
		SourceType:   common.SourceEnvVar,
		Confidence:   1.0,
		Tags:         []string{"environment", "core"},
	},
	{
		ID:            "c_stdin",
		Framework:     "core",
		Language:      "c",
		Name:          "stdin",
		Description:   "Standard input stream",
		PropertyPattern: "^stdin$",
		SourceType:   common.SourceStdin,
		Confidence:   1.0,
		Tags:         []string{"stdin", "core"},
	},
}

// Input function patterns
var inputFunctionPatterns = []*common.FrameworkPattern{
	{
		ID:            "c_getenv",
		Framework:     "core",
		Language:      "c",
		Name:          "getenv()",
		Description:   "Get environment variable by name",
		MethodPattern: "^getenv$",
		SourceType:   common.SourceEnvVar,
		SourceKey:    `getenv\s*\(\s*"([^"]+)"`,
		Confidence:   1.0,
		Tags:         []string{"environment", "core"},
	},
	{
		ID:            "c_gets",
		Framework:     "core",
		Language:      "c",
		Name:          "gets()",
		Description:   "Read string from stdin (unsafe, deprecated)",
		MethodPattern: "^gets$",
		SourceType:   common.SourceStdin,
		Confidence:   1.0,
		Tags:         []string{"stdin", "core", "unsafe"},
	},
	{
		ID:            "c_fgets",
		Framework:     "core",
		Language:      "c",
		Name:          "fgets()",
		Description:   "Read string from stream",
		MethodPattern: "^fgets$",
		SourceType:   common.SourceUserInput,
		Confidence:   0.9,
		Tags:         []string{"stdin", "file", "core"},
	},
	{
		ID:            "c_scanf",
		Framework:     "core",
		Language:      "c",
		Name:          "scanf()",
		Description:   "Formatted input from stdin",
		MethodPattern: "^scanf$",
		SourceType:   common.SourceStdin,
		Confidence:   1.0,
		Tags:         []string{"stdin", "core"},
	},
	{
		ID:            "c_fscanf",
		Framework:     "core",
		Language:      "c",
		Name:          "fscanf()",
		Description:   "Formatted input from stream",
		MethodPattern: "^fscanf$",
		SourceType:   common.SourceUserInput,
		Confidence:   0.9,
		Tags:         []string{"stdin", "file", "core"},
	},
	{
		ID:            "c_getchar",
		Framework:     "core",
		Language:      "c",
		Name:          "getchar()",
		Description:   "Read single character from stdin",
		MethodPattern: "^getchar$",
		SourceType:   common.SourceStdin,
		Confidence:   1.0,
		Tags:         []string{"stdin", "core"},
	},
	{
		ID:            "c_fread",
		Framework:     "core",
		Language:      "c",
		Name:          "fread()",
		Description:   "Binary read from stream",
		MethodPattern: "^fread$",
		SourceType:   common.SourceFile,
		Confidence:   0.9,
		Tags:         []string{"file", "core"},
	},
	{
		ID:            "c_read",
		Framework:     "core",
		Language:      "c",
		Name:          "read()",
		Description:   "POSIX read from file descriptor",
		MethodPattern: "^read$",
		SourceType:   common.SourceUserInput,
		Confidence:   0.85,
		Tags:         []string{"file", "network", "core"},
	},
	{
		ID:            "c_recv",
		Framework:     "core",
		Language:      "c",
		Name:          "recv()",
		Description:   "Receive data from socket",
		MethodPattern: "^recv$",
		SourceType:   common.SourceNetwork,
		Confidence:   1.0,
		Tags:         []string{"network", "core"},
	},
	{
		ID:            "c_recvfrom",
		Framework:     "core",
		Language:      "c",
		Name:          "recvfrom()",
		Description:   "Receive data from socket with address",
		MethodPattern: "^recvfrom$",
		SourceType:   common.SourceNetwork,
		Confidence:   1.0,
		Tags:         []string{"network", "core"},
	},
}

func init() {
	Registry.RegisterAll(cgiPatterns)
	Registry.RegisterAll(corePatterns)
	Registry.RegisterAll(inputFunctionPatterns)

	// Register framework detector for CGI programs
	common.RegisterFrameworkDetector(&common.FrameworkDetector{
		Framework:  "cgi",
		Indicators: []string{"cgi-bin/", ".cgi"},
	})
}
