// Package php - codeigniter.go provides CodeIgniter framework input patterns
package php

import (
	"github.com/hatlesswizard/inputtracer/pkg/sources/common"
)

var codeigniterPatterns = []*common.FrameworkPattern{
	{
		ID:            "codeigniter_input_get",
		Framework:     "codeigniter",
		Language:      "php",
		Name:          "CodeIgniter $this->input->get()",
		Description:   "CodeIgniter input class get() method",
		ClassPattern:  "^CI_Input$",
		MethodPattern: "^get$",
		SourceType:    common.SourceHTTPGet,
		CarrierClass:  "CI_Input",
		PopulatedFrom: []string{"$_GET"},
		Confidence:    0.9,
		Tags:          []string{"framework", "legacy"},
	},
	{
		ID:            "codeigniter_input_post",
		Framework:     "codeigniter",
		Language:      "php",
		Name:          "CodeIgniter $this->input->post()",
		Description:   "CodeIgniter input class post() method",
		ClassPattern:  "^CI_Input$",
		MethodPattern: "^post$",
		SourceType:    common.SourceHTTPPost,
		CarrierClass:  "CI_Input",
		PopulatedFrom: []string{"$_POST"},
		Confidence:    0.9,
		Tags:          []string{"framework", "legacy"},
	},
	{
		ID:            "codeigniter_input_cookie",
		Framework:     "codeigniter",
		Language:      "php",
		Name:          "CodeIgniter $this->input->cookie()",
		Description:   "CodeIgniter input class cookie() method",
		ClassPattern:  "^CI_Input$",
		MethodPattern: "^cookie$",
		SourceType:    common.SourceHTTPCookie,
		CarrierClass:  "CI_Input",
		PopulatedFrom: []string{"$_COOKIE"},
		Confidence:    0.9,
		Tags:          []string{"framework", "legacy"},
	},
	{
		ID:            "codeigniter_input_server",
		Framework:     "codeigniter",
		Language:      "php",
		Name:          "CodeIgniter $this->input->server()",
		Description:   "CodeIgniter input class server() method",
		ClassPattern:  "^CI_Input$",
		MethodPattern: "^server$",
		SourceType:    common.SourceHTTPHeader,
		CarrierClass:  "CI_Input",
		PopulatedFrom: []string{"$_SERVER"},
		Confidence:    0.9,
		Tags:          []string{"framework", "legacy"},
	},
	{
		ID:            "codeigniter_input_get_post",
		Framework:     "codeigniter",
		Language:      "php",
		Name:          "CodeIgniter $this->input->get_post()",
		Description:   "CodeIgniter input class get_post() method (checks GET then POST)",
		ClassPattern:  "^CI_Input$",
		MethodPattern: "^get_post$",
		SourceType:    common.SourceUserInput,
		CarrierClass:  "CI_Input",
		PopulatedFrom: []string{"$_GET", "$_POST"},
		Confidence:    0.9,
		Tags:          []string{"framework", "legacy"},
	},
	{
		ID:            "codeigniter_input_post_get",
		Framework:     "codeigniter",
		Language:      "php",
		Name:          "CodeIgniter $this->input->post_get()",
		Description:   "CodeIgniter input class post_get() method (checks POST then GET)",
		ClassPattern:  "^CI_Input$",
		MethodPattern: "^post_get$",
		SourceType:    common.SourceUserInput,
		CarrierClass:  "CI_Input",
		PopulatedFrom: []string{"$_POST", "$_GET"},
		Confidence:    0.9,
		Tags:          []string{"framework", "legacy"},
	},
	{
		ID:            "codeigniter_input_ip_address",
		Framework:     "codeigniter",
		Language:      "php",
		Name:          "CodeIgniter $this->input->ip_address()",
		Description:   "CodeIgniter input class ip_address() method",
		ClassPattern:  "^CI_Input$",
		MethodPattern: "^ip_address$",
		SourceType:    common.SourceNetwork,
		CarrierClass:  "CI_Input",
		Confidence:    0.9,
		Tags:          []string{"framework", "legacy"},
	},
	{
		ID:            "codeigniter_input_user_agent",
		Framework:     "codeigniter",
		Language:      "php",
		Name:          "CodeIgniter $this->input->user_agent()",
		Description:   "CodeIgniter input class user_agent() method",
		ClassPattern:  "^CI_Input$",
		MethodPattern: "^user_agent$",
		SourceType:    common.SourceHTTPHeader,
		CarrierClass:  "CI_Input",
		Confidence:    0.9,
		Tags:          []string{"framework", "legacy"},
	},
	// CodeIgniter 4 patterns
	{
		ID:            "codeigniter4_request_getGet",
		Framework:     "codeigniter",
		Language:      "php",
		Name:          "CodeIgniter 4 $request->getGet()",
		Description:   "CodeIgniter 4 IncomingRequest getGet() method",
		ClassPattern:  "^(CodeIgniter\\\\HTTP\\\\)?IncomingRequest$",
		MethodPattern: "^getGet$",
		SourceType:    common.SourceHTTPGet,
		CarrierClass:  "CodeIgniter\\HTTP\\IncomingRequest",
		PopulatedFrom: []string{"$_GET"},
		Confidence:    0.95,
		Tags:          []string{"framework", "modern"},
	},
	{
		ID:            "codeigniter4_request_getPost",
		Framework:     "codeigniter",
		Language:      "php",
		Name:          "CodeIgniter 4 $request->getPost()",
		Description:   "CodeIgniter 4 IncomingRequest getPost() method",
		ClassPattern:  "^(CodeIgniter\\\\HTTP\\\\)?IncomingRequest$",
		MethodPattern: "^getPost$",
		SourceType:    common.SourceHTTPPost,
		CarrierClass:  "CodeIgniter\\HTTP\\IncomingRequest",
		PopulatedFrom: []string{"$_POST"},
		Confidence:    0.95,
		Tags:          []string{"framework", "modern"},
	},
	{
		ID:            "codeigniter4_request_getJSON",
		Framework:     "codeigniter",
		Language:      "php",
		Name:          "CodeIgniter 4 $request->getJSON()",
		Description:   "CodeIgniter 4 IncomingRequest getJSON() method",
		ClassPattern:  "^(CodeIgniter\\\\HTTP\\\\)?IncomingRequest$",
		MethodPattern: "^getJSON$",
		SourceType:    common.SourceHTTPJSON,
		CarrierClass:  "CodeIgniter\\HTTP\\IncomingRequest",
		Confidence:    0.95,
		Tags:          []string{"framework", "modern"},
	},
}

func init() {
	Registry.RegisterAll(codeigniterPatterns)

	// Register framework detector
	common.RegisterFrameworkDetector(&common.FrameworkDetector{
		Framework:  "codeigniter",
		Indicators: []string{"system/core/CodeIgniter.php", "application/config/config.php", "spark"},
	})
}
