package php

import "github.com/hatlesswizard/inputtracer/pkg/sources/common"

// laravelExtraDefinitions returns definitions for Laravel request methods not
// covered by the auto-generated laravel.go. This includes typed accessors
// (Laravel 10+), FormRequest return-value sources, route/URL accessors, and the
// request() global helper function.
func laravelExtraDefinitions() []common.Definition {
	return []common.Definition{
		// ── Typed accessors (Laravel 10+) ─────────────────────────────────────
		{
			Name:         "->string()",
			Pattern:      `->\s*string\s*\(`,
			Language:     "php",
			Labels:       []common.InputLabel{common.LabelUserInput},
			Description:  "Laravel typed string accessor",
			NodeTypes:    []string{"member_call_expression"},
			KeyExtractor: `->\s*string\s*\(\s*['"]([^'"]+)['"]`,
		},
		{
			Name:         "->integer()",
			Pattern:      `->\s*integer\s*\(`,
			Language:     "php",
			Labels:       []common.InputLabel{common.LabelUserInput},
			Description:  "Laravel typed integer accessor",
			NodeTypes:    []string{"member_call_expression"},
			KeyExtractor: `->\s*integer\s*\(\s*['"]([^'"]+)['"]`,
		},
		{
			Name:         "->boolean()",
			Pattern:      `->\s*boolean\s*\(`,
			Language:     "php",
			Labels:       []common.InputLabel{common.LabelUserInput},
			Description:  "Laravel typed boolean accessor",
			NodeTypes:    []string{"member_call_expression"},
			KeyExtractor: `->\s*boolean\s*\(\s*['"]([^'"]+)['"]`,
		},
		{
			Name:         "->float()",
			Pattern:      `->\s*float\s*\(`,
			Language:     "php",
			Labels:       []common.InputLabel{common.LabelUserInput},
			Description:  "Laravel typed float accessor",
			NodeTypes:    []string{"member_call_expression"},
			KeyExtractor: `->\s*float\s*\(\s*['"]([^'"]+)['"]`,
		},
		{
			Name:         "->date()",
			Pattern:      `->\s*date\s*\(`,
			Language:     "php",
			Labels:       []common.InputLabel{common.LabelUserInput},
			Description:  "Laravel typed date accessor",
			NodeTypes:    []string{"member_call_expression"},
			KeyExtractor: `->\s*date\s*\(\s*['"]([^'"]+)['"]`,
		},
		{
			Name:         "->enum()",
			Pattern:      `->\s*enum\s*\(`,
			Language:     "php",
			Labels:       []common.InputLabel{common.LabelUserInput},
			Description:  "Laravel typed enum accessor",
			NodeTypes:    []string{"member_call_expression"},
			KeyExtractor: `->\s*enum\s*\(\s*['"]([^'"]+)['"]`,
		},

		// ── Collection / subset accessors ─────────────────────────────────────
		{
			Name:         "->collect()",
			Pattern:      `->\s*collect\s*\(`,
			Language:     "php",
			Labels:       []common.InputLabel{common.LabelUserInput},
			Description:  "Laravel collect input as Collection",
			NodeTypes:    []string{"member_call_expression"},
			KeyExtractor: `->\s*collect\s*\(\s*['"]([^'"]+)['"]`,
		},
		{
			Name:         "->only()",
			Pattern:      `->\s*only\s*\(`,
			Language:     "php",
			Labels:       []common.InputLabel{common.LabelUserInput},
			Description:  "Laravel get only specified keys",
			NodeTypes:    []string{"member_call_expression"},
		},
		{
			Name:         "->except()",
			Pattern:      `->\s*except\s*\(`,
			Language:     "php",
			Labels:       []common.InputLabel{common.LabelUserInput},
			Description:  "Laravel get all except specified keys",
			NodeTypes:    []string{"member_call_expression"},
		},

		// ── FormRequest return-value sources ──────────────────────────────────
		{
			Name:        "->validated()",
			Pattern:     `->\s*validated\s*\(`,
			Language:    "php",
			Labels:      []common.InputLabel{common.LabelUserInput},
			Description: "Laravel FormRequest validated data",
			NodeTypes:   []string{"member_call_expression"},
		},
		{
			Name:        "->safe()",
			Pattern:     `->\s*safe\s*\(`,
			Language:    "php",
			Labels:      []common.InputLabel{common.LabelUserInput},
			Description: "Laravel FormRequest safe data",
			NodeTypes:   []string{"member_call_expression"},
		},

		// ── Route / URL parameter access ──────────────────────────────────────
		{
			Name:         "->route()",
			Pattern:      `->\s*route\s*\(`,
			Language:     "php",
			Labels:       []common.InputLabel{common.LabelUserInput},
			Description:  "Laravel route parameter",
			NodeTypes:    []string{"member_call_expression"},
			KeyExtractor: `->\s*route\s*\(\s*['"]([^'"]+)['"]`,
		},
		{
			Name:        "->segment()",
			Pattern:     `->\s*segment\s*\(`,
			Language:    "php",
			Labels:      []common.InputLabel{common.LabelUserInput},
			Description: "Laravel URL segment accessor",
			NodeTypes:   []string{"member_call_expression"},
		},

		// ── Global helper function ────────────────────────────────────────────
		{
			Name:         "request()",
			Pattern:      `\brequest\s*\(`,
			Language:     "php",
			Labels:       []common.InputLabel{common.LabelUserInput},
			Description:  "Laravel request() global helper",
			NodeTypes:    []string{"function_call_expression"},
			KeyExtractor: `\brequest\s*\(\s*['"]([^'"]+)['"]`,
		},

		// ── Request metadata accessors ────────────────────────────────────────
		{
			Name:        "->ip()",
			Pattern:     `->\s*ip\s*\(`,
			Language:    "php",
			Labels:      []common.InputLabel{common.LabelHTTPHeader, common.LabelUserInput},
			Description: "Laravel client IP",
			NodeTypes:   []string{"member_call_expression"},
		},
		{
			Name:        "->url()",
			Pattern:     `->\s*url\s*\(`,
			Language:    "php",
			Labels:      []common.InputLabel{common.LabelUserInput},
			Description: "Laravel request URL",
			NodeTypes:   []string{"member_call_expression"},
		},
		{
			Name:        "->fullUrl()",
			Pattern:     `->\s*fullUrl\s*\(`,
			Language:    "php",
			Labels:      []common.InputLabel{common.LabelUserInput},
			Description: "Laravel full request URL",
			NodeTypes:   []string{"member_call_expression"},
		},
		{
			Name:        "->path()",
			Pattern:     `->\s*path\s*\(`,
			Language:    "php",
			Labels:      []common.InputLabel{common.LabelUserInput},
			Description: "Laravel request path",
			NodeTypes:   []string{"member_call_expression"},
		},
		{
			Name:        "->method()",
			Pattern:     `->\s*method\s*\(`,
			Language:    "php",
			Labels:      []common.InputLabel{common.LabelUserInput},
			Description: "Laravel HTTP method",
			NodeTypes:   []string{"member_call_expression"},
		},
		{
			Name:        "->userAgent()",
			Pattern:     `->\s*userAgent\s*\(`,
			Language:    "php",
			Labels:      []common.InputLabel{common.LabelHTTPHeader, common.LabelUserInput},
			Description: "Laravel User-Agent header",
			NodeTypes:   []string{"member_call_expression"},
		},
		{
			Name:        "->getClientIp()",
			Pattern:     `->\s*getClientIp\s*\(`,
			Language:    "php",
			Labels:      []common.InputLabel{common.LabelHTTPHeader, common.LabelUserInput},
			Description: "Symfony/Laravel client IP",
			NodeTypes:   []string{"member_call_expression"},
		},
		{
			Name:        "->getClientIps()",
			Pattern:     `->\s*getClientIps\s*\(`,
			Language:    "php",
			Labels:      []common.InputLabel{common.LabelHTTPHeader, common.LabelUserInput},
			Description: "Symfony/Laravel all client IPs",
			NodeTypes:   []string{"member_call_expression"},
		},

		// Methods that were only registered as FrameworkPatterns (semantic path)
		// but need explicit Definitions for forward source detection.
		{
			Name:        "->bearerToken()",
			Pattern:     `->\s*bearerToken\s*\(`,
			Language:    "php",
			Labels:      []common.InputLabel{common.LabelHTTPHeader, common.LabelUserInput},
			Description: "Laravel bearer token from Authorization header",
			NodeTypes:   []string{"member_call_expression"},
		},
		{
			Name:        "->allFiles()",
			Pattern:     `->\s*allFiles\s*\(`,
			Language:    "php",
			Labels:      []common.InputLabel{common.LabelFile, common.LabelUserInput},
			Description: "Laravel all uploaded files",
			NodeTypes:   []string{"member_call_expression"},
		},
		{
			Name:        "->json()",
			Pattern:     `->\s*json\s*\(`,
			Language:    "php",
			Labels:      []common.InputLabel{common.LabelHTTPBody, common.LabelUserInput},
			Description: "Laravel JSON request body",
			NodeTypes:   []string{"member_call_expression"},
		},
		{
			Name:        "->toArray()",
			Pattern:     `->\s*toArray\s*\(`,
			Language:    "php",
			Labels:      []common.InputLabel{common.LabelHTTPBody, common.LabelUserInput},
			Description: "Laravel/Symfony request as array",
			NodeTypes:   []string{"member_call_expression"},
		},
		{
			Name:         "->old()",
			Pattern:      `->\s*old\s*\(`,
			Language:     "php",
			Labels:       []common.InputLabel{common.LabelUserInput},
			Description:  "Laravel old input from session flash",
			NodeTypes:    []string{"member_call_expression"},
			KeyExtractor: `->\s*old\s*\(\s*['"]([^'"]+)['"]`,
		},
		{
			Name:        "->user()",
			Pattern:     `->\s*user\s*\(`,
			Language:    "php",
			Labels:      []common.InputLabel{common.LabelUserInput},
			Description: "Laravel authenticated user accessor",
			NodeTypes:   []string{"member_call_expression"},
		},
		{
			Name:         "->hasCookie()",
			Pattern:      `->\s*hasCookie\s*\(`,
			Language:     "php",
			Labels:       []common.InputLabel{common.LabelHTTPCookie, common.LabelUserInput},
			Description:  "Laravel cookie existence check",
			NodeTypes:    []string{"member_call_expression"},
			KeyExtractor: `->\s*hasCookie\s*\(\s*['"]([^'"]+)['"]`,
		},
		{
			Name:         "->hasFile()",
			Pattern:      `->\s*hasFile\s*\(`,
			Language:     "php",
			Labels:       []common.InputLabel{common.LabelFile, common.LabelUserInput},
			Description:  "Laravel file upload existence check",
			NodeTypes:    []string{"member_call_expression"},
			KeyExtractor: `->\s*hasFile\s*\(\s*['"]([^'"]+)['"]`,
		},
		{
			Name:         "->hasHeader()",
			Pattern:      `->\s*hasHeader\s*\(`,
			Language:     "php",
			Labels:       []common.InputLabel{common.LabelHTTPHeader, common.LabelUserInput},
			Description:  "Laravel header existence check",
			NodeTypes:    []string{"member_call_expression"},
			KeyExtractor: `->\s*hasHeader\s*\(\s*['"]([^'"]+)['"]`,
		},
		{
			Name:        "->getAcceptableContentTypes()",
			Pattern:     `->\s*getAcceptableContentTypes\s*\(`,
			Language:    "php",
			Labels:      []common.InputLabel{common.LabelHTTPHeader, common.LabelUserInput},
			Description: "Laravel acceptable content types from Accept header",
			NodeTypes:   []string{"member_call_expression"},
		},
		{
			Name:        "->uri()",
			Pattern:     `->\s*uri\s*\(`,
			Language:    "php",
			Labels:      []common.InputLabel{common.LabelUserInput},
			Description: "Laravel request URI",
			NodeTypes:   []string{"member_call_expression"},
		},
		{
			Name:         "->offsetGet()",
			Pattern:      `->\s*offsetGet\s*\(`,
			Language:     "php",
			Labels:       []common.InputLabel{common.LabelUserInput},
			Description:  "Laravel ArrayAccess offsetGet",
			NodeTypes:    []string{"member_call_expression"},
			KeyExtractor: `->\s*offsetGet\s*\(\s*['"]([^'"]+)['"]`,
		},
	}
}
