// Package php - laravel.go provides Laravel framework input patterns
package php

import (
	"github.com/hatlesswizard/inputtracer/pkg/sources/common"
)

var laravelPatterns = []*common.FrameworkPattern{
	{
		ID:            "laravel_request_input",
		Framework:     "laravel",
		Language:      "php",
		Name:          "Laravel $request->input()",
		Description:   "Laravel request input method returns GET and POST data",
		ClassPattern:  "^(Illuminate\\\\Http\\\\)?Request$",
		MethodPattern: "^input$",
		SourceType:    common.SourceHTTPGet,
		CarrierClass:  "Illuminate\\Http\\Request",
		PopulatedFrom: []string{"$_GET", "$_POST"},
		Confidence:    0.95,
		Tags:          []string{"framework", "modern"},
	},
	{
		ID:            "laravel_request_all",
		Framework:     "laravel",
		Language:      "php",
		Name:          "Laravel $request->all()",
		Description:   "Laravel request all() returns all input data",
		ClassPattern:  "^(Illuminate\\\\Http\\\\)?Request$",
		MethodPattern: "^all$",
		SourceType:    common.SourceHTTPGet,
		CarrierClass:  "Illuminate\\Http\\Request",
		PopulatedFrom: []string{"$_GET", "$_POST"},
		Confidence:    0.95,
		Tags:          []string{"framework", "modern"},
	},
	{
		ID:            "laravel_request_query",
		Framework:     "laravel",
		Language:      "php",
		Name:          "Laravel $request->query()",
		Description:   "Laravel request query() returns query string parameters",
		ClassPattern:  "^(Illuminate\\\\Http\\\\)?Request$",
		MethodPattern: "^query$",
		SourceType:    common.SourceHTTPGet,
		CarrierClass:  "Illuminate\\Http\\Request",
		PopulatedFrom: []string{"$_GET"},
		Confidence:    0.95,
		Tags:          []string{"framework", "modern"},
	},
	{
		ID:            "laravel_request_post",
		Framework:     "laravel",
		Language:      "php",
		Name:          "Laravel $request->post()",
		Description:   "Laravel request post() returns POST parameters",
		ClassPattern:  "^(Illuminate\\\\Http\\\\)?Request$",
		MethodPattern: "^post$",
		SourceType:    common.SourceHTTPPost,
		CarrierClass:  "Illuminate\\Http\\Request",
		PopulatedFrom: []string{"$_POST"},
		Confidence:    0.95,
		Tags:          []string{"framework", "modern"},
	},
	{
		ID:            "laravel_request_cookie",
		Framework:     "laravel",
		Language:      "php",
		Name:          "Laravel $request->cookie()",
		Description:   "Laravel request cookie() returns cookie values",
		ClassPattern:  "^(Illuminate\\\\Http\\\\)?Request$",
		MethodPattern: "^cookie$",
		SourceType:    common.SourceHTTPCookie,
		CarrierClass:  "Illuminate\\Http\\Request",
		PopulatedFrom: []string{"$_COOKIE"},
		Confidence:    0.95,
		Tags:          []string{"framework", "modern"},
	},
	{
		ID:            "laravel_request_header",
		Framework:     "laravel",
		Language:      "php",
		Name:          "Laravel $request->header()",
		Description:   "Laravel request header() returns HTTP headers",
		ClassPattern:  "^(Illuminate\\\\Http\\\\)?Request$",
		MethodPattern: "^header$",
		SourceType:    common.SourceHTTPHeader,
		CarrierClass:  "Illuminate\\Http\\Request",
		PopulatedFrom: []string{"$_SERVER"},
		Confidence:    0.95,
		Tags:          []string{"framework", "modern"},
	},
	{
		ID:            "laravel_request_file",
		Framework:     "laravel",
		Language:      "php",
		Name:          "Laravel $request->file()",
		Description:   "Laravel request file() returns uploaded files",
		ClassPattern:  "^(Illuminate\\\\Http\\\\)?Request$",
		MethodPattern: "^file$",
		SourceType:    common.SourceHTTPFile,
		CarrierClass:  "Illuminate\\Http\\Request",
		PopulatedFrom: []string{"$_FILES"},
		Confidence:    0.95,
		Tags:          []string{"framework", "modern"},
	},
	{
		ID:            "laravel_request_get",
		Framework:     "laravel",
		Language:      "php",
		Name:          "Laravel $request->get()",
		Description:   "Laravel request get() returns input value by key",
		ClassPattern:  "^(Illuminate\\\\Http\\\\)?Request$",
		MethodPattern: "^get$",
		SourceType:    common.SourceUserInput,
		CarrierClass:  "Illuminate\\Http\\Request",
		PopulatedFrom: []string{"$_GET", "$_POST"},
		Confidence:    0.9,
		Tags:          []string{"framework", "modern"},
	},
	{
		ID:            "laravel_request_only",
		Framework:     "laravel",
		Language:      "php",
		Name:          "Laravel $request->only()",
		Description:   "Laravel request only() returns subset of input",
		ClassPattern:  "^(Illuminate\\\\Http\\\\)?Request$",
		MethodPattern: "^only$",
		SourceType:    common.SourceUserInput,
		CarrierClass:  "Illuminate\\Http\\Request",
		PopulatedFrom: []string{"$_GET", "$_POST"},
		Confidence:    0.95,
		Tags:          []string{"framework", "modern"},
	},
	{
		ID:            "laravel_request_except",
		Framework:     "laravel",
		Language:      "php",
		Name:          "Laravel $request->except()",
		Description:   "Laravel request except() returns input excluding specified keys",
		ClassPattern:  "^(Illuminate\\\\Http\\\\)?Request$",
		MethodPattern: "^except$",
		SourceType:    common.SourceUserInput,
		CarrierClass:  "Illuminate\\Http\\Request",
		PopulatedFrom: []string{"$_GET", "$_POST"},
		Confidence:    0.95,
		Tags:          []string{"framework", "modern"},
	},
	{
		ID:            "laravel_request_validated",
		Framework:     "laravel",
		Language:      "php",
		Name:          "Laravel $request->validated()",
		Description:   "Laravel validated() returns validated input data",
		ClassPattern:  "^(Illuminate\\\\Http\\\\)?Request$",
		MethodPattern: "^validated$",
		SourceType:    common.SourceUserInput,
		CarrierClass:  "Illuminate\\Http\\Request",
		PopulatedFrom: []string{"$_GET", "$_POST"},
		Confidence:    0.9, // Validated but still user input
		Tags:          []string{"framework", "modern", "validated"},
	},
}

func init() {
	Registry.RegisterAll(laravelPatterns)

	// Register framework detector
	common.RegisterFrameworkDetector(&common.FrameworkDetector{
		Framework:  "laravel",
		Indicators: []string{"artisan", "bootstrap/app.php", "config/app.php"},
	})
}
