// Package php - symfony.go provides Symfony framework input patterns
package php

import (
	"github.com/hatlesswizard/inputtracer/pkg/sources/common"
)

var symfonyPatterns = []*common.FrameworkPattern{
	{
		ID:              "symfony_request_query",
		Framework:       "symfony",
		Language:        "php",
		Name:            "Symfony $request->query",
		Description:     "Symfony request query bag contains GET parameters",
		ClassPattern:    "^(Symfony\\\\Component\\\\HttpFoundation\\\\)?Request$",
		PropertyPattern: "^query$",
		SourceType:      common.SourceHTTPGet,
		CarrierClass:    "Symfony\\Component\\HttpFoundation\\Request",
		CarrierProperty: "query",
		PopulatedFrom:   []string{"$_GET"},
		Confidence:      0.95,
		Tags:            []string{"framework", "enterprise"},
	},
	{
		ID:              "symfony_request_request",
		Framework:       "symfony",
		Language:        "php",
		Name:            "Symfony $request->request",
		Description:     "Symfony request bag contains POST parameters",
		ClassPattern:    "^(Symfony\\\\Component\\\\HttpFoundation\\\\)?Request$",
		PropertyPattern: "^request$",
		SourceType:      common.SourceHTTPPost,
		CarrierClass:    "Symfony\\Component\\HttpFoundation\\Request",
		CarrierProperty: "request",
		PopulatedFrom:   []string{"$_POST"},
		Confidence:      0.95,
		Tags:            []string{"framework", "enterprise"},
	},
	{
		ID:              "symfony_request_cookies",
		Framework:       "symfony",
		Language:        "php",
		Name:            "Symfony $request->cookies",
		Description:     "Symfony cookies bag contains cookie values",
		ClassPattern:    "^(Symfony\\\\Component\\\\HttpFoundation\\\\)?Request$",
		PropertyPattern: "^cookies$",
		SourceType:      common.SourceHTTPCookie,
		CarrierClass:    "Symfony\\Component\\HttpFoundation\\Request",
		CarrierProperty: "cookies",
		PopulatedFrom:   []string{"$_COOKIE"},
		Confidence:      0.95,
		Tags:            []string{"framework", "enterprise"},
	},
	{
		ID:              "symfony_request_headers",
		Framework:       "symfony",
		Language:        "php",
		Name:            "Symfony $request->headers",
		Description:     "Symfony headers bag contains HTTP headers",
		ClassPattern:    "^(Symfony\\\\Component\\\\HttpFoundation\\\\)?Request$",
		PropertyPattern: "^headers$",
		SourceType:      common.SourceHTTPHeader,
		CarrierClass:    "Symfony\\Component\\HttpFoundation\\Request",
		CarrierProperty: "headers",
		PopulatedFrom:   []string{"$_SERVER"},
		Confidence:      0.95,
		Tags:            []string{"framework", "enterprise"},
	},
	{
		ID:              "symfony_request_files",
		Framework:       "symfony",
		Language:        "php",
		Name:            "Symfony $request->files",
		Description:     "Symfony files bag contains uploaded files",
		ClassPattern:    "^(Symfony\\\\Component\\\\HttpFoundation\\\\)?Request$",
		PropertyPattern: "^files$",
		SourceType:      common.SourceHTTPFile,
		CarrierClass:    "Symfony\\Component\\HttpFoundation\\Request",
		CarrierProperty: "files",
		PopulatedFrom:   []string{"$_FILES"},
		Confidence:      0.95,
		Tags:            []string{"framework", "enterprise"},
	},
	{
		ID:              "symfony_request_server",
		Framework:       "symfony",
		Language:        "php",
		Name:            "Symfony $request->server",
		Description:     "Symfony server bag contains server parameters",
		ClassPattern:    "^(Symfony\\\\Component\\\\HttpFoundation\\\\)?Request$",
		PropertyPattern: "^server$",
		SourceType:      common.SourceHTTPHeader,
		CarrierClass:    "Symfony\\Component\\HttpFoundation\\Request",
		CarrierProperty: "server",
		PopulatedFrom:   []string{"$_SERVER"},
		Confidence:      0.95,
		Tags:            []string{"framework", "enterprise"},
	},
	{
		ID:              "symfony_request_attributes",
		Framework:       "symfony",
		Language:        "php",
		Name:            "Symfony $request->attributes",
		Description:     "Symfony attributes bag (route parameters, etc.)",
		ClassPattern:    "^(Symfony\\\\Component\\\\HttpFoundation\\\\)?Request$",
		PropertyPattern: "^attributes$",
		SourceType:      common.SourceHTTPPath,
		CarrierClass:    "Symfony\\Component\\HttpFoundation\\Request",
		CarrierProperty: "attributes",
		Confidence:      0.9,
		Tags:            []string{"framework", "enterprise"},
	},
	{
		ID:            "symfony_request_get",
		Framework:     "symfony",
		Language:      "php",
		Name:          "Symfony $request->get()",
		Description:   "Symfony request get() method retrieves input value",
		ClassPattern:  "^(Symfony\\\\Component\\\\HttpFoundation\\\\)?Request$",
		MethodPattern: "^get$",
		SourceType:    common.SourceUserInput,
		CarrierClass:  "Symfony\\Component\\HttpFoundation\\Request",
		PopulatedFrom: []string{"$_GET", "$_POST"},
		Confidence:    0.9,
		Tags:          []string{"framework", "enterprise"},
	},
	{
		ID:            "symfony_request_getContent",
		Framework:     "symfony",
		Language:      "php",
		Name:          "Symfony $request->getContent()",
		Description:   "Symfony request getContent() returns raw request body",
		ClassPattern:  "^(Symfony\\\\Component\\\\HttpFoundation\\\\)?Request$",
		MethodPattern: "^getContent$",
		SourceType:    common.SourceHTTPBody,
		CarrierClass:  "Symfony\\Component\\HttpFoundation\\Request",
		Confidence:    0.95,
		Tags:          []string{"framework", "enterprise"},
	},
	// ParameterBag methods
	{
		ID:            "symfony_parameterbag_get",
		Framework:     "symfony",
		Language:      "php",
		Name:          "Symfony ParameterBag->get()",
		Description:   "Symfony ParameterBag get() returns parameter value",
		ClassPattern:  "^(Symfony\\\\Component\\\\HttpFoundation\\\\)?ParameterBag$",
		MethodPattern: "^get$",
		SourceType:    common.SourceUserInput,
		Confidence:    0.9,
		Tags:          []string{"framework", "enterprise"},
	},
	{
		ID:            "symfony_parameterbag_all",
		Framework:     "symfony",
		Language:      "php",
		Name:          "Symfony ParameterBag->all()",
		Description:   "Symfony ParameterBag all() returns all parameters",
		ClassPattern:  "^(Symfony\\\\Component\\\\HttpFoundation\\\\)?ParameterBag$",
		MethodPattern: "^all$",
		SourceType:    common.SourceUserInput,
		Confidence:    0.9,
		Tags:          []string{"framework", "enterprise"},
	},
}

func init() {
	Registry.RegisterAll(symfonyPatterns)

	// Register framework detector
	common.RegisterFrameworkDetector(&common.FrameworkDetector{
		Framework:  "symfony",
		Indicators: []string{"symfony.lock", "config/bundles.php", "src/Kernel.php"},
	})
}
